// Code generated by pgmesh. DO NOT EDIT.

package samepackage

import (
	"context"
	"database/sql"
	"errors"
	"github.com/jackc/pgx/v5"
)

// writeQueries exposes primary-capable generated queries.
type writeQueries struct {
	main    *Queries
	mirrors []*Queries
}

func newWriteQueries(q *Queries, mirrors ...*Queries) *writeQueries {
	return &writeQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *writeQueries) WithTx(tx pgx.Tx) *writeQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *writeQueries) WithMirrors(qs ...*writeQueries) *writeQueries {
	var mirrors []*Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *writeQueries) mirror(fn func(*Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// CopyUsers executes the generated CopyUsers query.
func (q *writeQueries) CopyUsers(ctx context.Context, arg []*CopyUsersParams) (int64, error) {
	rv0, err := q.main.CopyUsers(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.CopyUsers(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// CreateUser executes the generated CreateUser query.
func (q *writeQueries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	rv0, err := q.main.CreateUser(ctx, arg)
	if err != nil {
		var zero0 *User
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.CreateUser(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// DeleteAllUsers executes the generated DeleteAllUsers query.
func (q *writeQueries) DeleteAllUsers(ctx context.Context) error {
	if err := q.main.DeleteAllUsers(ctx); err != nil {
		return err
	}
	return q.mirror(func(mirror *Queries) error {
		return mirror.DeleteAllUsers(ctx)
	})
}

// DeleteAllUsersByName executes the generated DeleteAllUsersByName query.
func (q *writeQueries) DeleteAllUsersByName(ctx context.Context, name string) (int64, error) {
	rv0, err := q.main.DeleteAllUsersByName(ctx, name)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.DeleteAllUsersByName(ctx, name)
		return err
	})
	return rv0, mirrorErr
}

// UpdateUserName executes the generated UpdateUserName query.
func (q *writeQueries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error) {
	rv0, err := q.main.UpdateUserName(ctx, arg)
	if err != nil {
		var zero0 *User
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.UpdateUserName(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}
