// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package samepackage

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisState string

const (
	AnalysisStatePending  AnalysisState = "pending"
	AnalysisStateComplete AnalysisState = "complete"
)

func (e *AnalysisState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalysisState(s)
	case string:
		*e = AnalysisState(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalysisState: %T", src)
	}
	return nil
}

type NullAnalysisState struct {
	AnalysisState AnalysisState
	Valid         bool // Valid is true if AnalysisState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalysisState) Scan(value interface{}) error {
	if value == nil {
		ns.AnalysisState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalysisState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalysisState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalysisState), nil
}

type Analysis struct {
	ID           int64
	TenantID     int64
	Description  *string
	State        NullAnalysisState
	Source       netip.Addr
	ActiveWindow pgtype.Range[pgtype.Timestamptz]
}

type Message struct {
	ID              interface{}
	UserID          int64
	ToUserOrGroupID int64
	InGroup         bool
	CreatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type MessageInbox struct {
	ID              int64
	ToUserOrGroupID *int64
}

type User struct {
	ID       int64
	TenantID int64
	Name     string
}
