// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package sharded

import (
	"context"
)

// iteratorForCopyAccounts implements pgx.CopyFromSource.
type iteratorForCopyAccounts struct {
	rows                 []*CopyAccountsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyAccounts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyAccounts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TenantID,
		r.rows[0].DisplayName,
	}, nil
}

func (r iteratorForCopyAccounts) Err() error {
	return nil
}

// kind: write
// shard: tenantKey(tenant_id)
// store: Accounts
func (q *Queries) CopyAccounts(ctx context.Context, arg []*CopyAccountsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"accounts"}, []string{"id", "tenant_id", "display_name"}, &iteratorForCopyAccounts{rows: arg})
}
