// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	pgmesh "github.com/sundayfun/pgmesh"
)

// CountAccountsT combines SQL and routing parameters for CountAccounts.
type CountAccountsT struct {
	TenantKey
}

// ReportsReader exposes read queries in the Reports store group.
type ReportsReader interface {
	// CountAccounts executes the generated CountAccounts query.
	CountAccounts(ctx context.Context, arg *CountAccountsT, storeOptions ...QueryOption) (int64, error)
}

// ReportsWriter exposes write queries in the Reports store group.
type ReportsWriter interface {
}

// Reports exposes all queries in its generated store group.
type Reports interface {
	ReportsReader
	ReportsWriter
}

type telemetryReportsStore[SK any] struct {
	store  *meshStore[SK]
	target Reports
}

func (q *telemetryReportsStore[SK]) CountAccounts(ctx context.Context, arg *CountAccountsT, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Reports", "CountAccounts", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.CountAccounts(ctx, arg, storeOptions...)
}

// WithReportsFactory configures an optional wrapper for the Reports query group.
// A nil factory leaves the generated query group unwrapped.
func WithReportsFactory(createReports func(Reports) Reports) StoreOption {
	return func(options *storeOptions) { options.factories.Reports = createReports }
}

var _ Reports = (*groupedMeshStore[uint8])(nil)
var _ Reports = (*telemetryReportsStore[uint8])(nil)

// Reports returns the Reports query group.
func (q *meshStore[SK]) Reports() Reports {
	return q.groups.Reports
}

// CountAccounts executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CountAccounts(ctx context.Context, arg *CountAccountsT, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Reports", "CountAccounts", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.TenantKey(arg.TenantKey)
	}
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(pgmesh.RouteModeTransaction, 1)
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeTransaction)
		defer func() { physicalQuerySpan.End(err) }()
		return target.CountAccounts(ctx, arg.TenantKey.TenantID)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(pgmesh.RouteModePrimary, 1)
		route := shard.WriteRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModePrimary)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.CountAccounts(ctx, arg.TenantKey.TenantID)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(pgmesh.RouteModeRead, 1)
		route := shard.ReadRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeRead)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.CountAccounts(ctx, arg.TenantKey.TenantID)
	}
}
