// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	"github.com/jackc/pgx/v5"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *Queries
}

func newReadQueries(q *Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// CountAccounts executes the generated CountAccounts query.
func (q *readQueries) CountAccounts(ctx context.Context, tenantID int64) (int64, error) {
	rv0, err := q.main.CountAccounts(ctx, tenantID)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	return rv0, nil
}

// GetAccount executes the generated GetAccount query.
func (q *readQueries) GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error) {
	rv0, err := q.main.GetAccount(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	return rv0, nil
}

// ListAccountsByIDs executes the generated ListAccountsByIDs query.
func (q *readQueries) ListAccountsByIDs(ctx context.Context, ids []int64) ([]*Account, error) {
	rv0, err := q.main.ListAccountsByIDs(ctx, ids)
	if err != nil {
		var zero0 []*Account
		return zero0, err
	}
	return rv0, nil
}

// ListAllAccounts executes the generated ListAllAccounts query.
func (q *readQueries) ListAllAccounts(ctx context.Context) ([]*Account, error) {
	rv0, err := q.main.ListAllAccounts(ctx)
	if err != nil {
		var zero0 []*Account
		return zero0, err
	}
	return rv0, nil
}
