// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// CountAccounts executes the generated CountAccounts query.
	CountAccounts(ctx context.Context, tenantID int64) (int64, error)
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error)
	// ListAccountsByIDs executes the generated ListAccountsByIDs query.
	ListAccountsByIDs(ctx context.Context, ids []int64) ([]*Account, error)
	// ListAllAccounts executes the generated ListAllAccounts query.
	ListAllAccounts(ctx context.Context) ([]*Account, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CopyAccounts executes the generated CopyAccounts query.
	CopyAccounts(ctx context.Context, arg []*CopyAccountsParams) (int64, error)
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// Accounts returns the Accounts query group.
	Accounts() Accounts
	// Reports returns the Reports query group.
	Reports() Reports
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ Querier = (*queryStore)(nil)

// TenantKey is the shared shard key for the "tenantKey" route.
type TenantKey struct {
	TenantID int64
}

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// TenantKey resolves the "tenantKey" shard route.
	TenantKey(key TenantKey) SK
}
