// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	pgmesh "github.com/sundayfun/pgmesh"
)

// GetAccountT is the store parameter type for GetAccount.
type GetAccountT = GetAccountParams

// UpdateAccountNameT is the store parameter type for UpdateAccountName.
type UpdateAccountNameT = UpdateAccountNameParams

// UpsertAccountT is the store parameter type for UpsertAccount.
type UpsertAccountT = UpsertAccountParams

// AccountsReader exposes read queries in the Accounts store group.
type AccountsReader interface {
	// GetAccount executes the generated GetAccount query.
	GetAccount(ctx context.Context, arg *GetAccountT, storeOptions ...QueryOption) (*Account, error)
}

// AccountsWriter exposes write queries in the Accounts store group.
type AccountsWriter interface {
	// UpdateAccountName executes the generated UpdateAccountName query.
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameT, storeOptions ...QueryOption) (*Account, error)
	// UpsertAccount executes the generated UpsertAccount query.
	UpsertAccount(ctx context.Context, arg *UpsertAccountT, storeOptions ...QueryOption) (*Account, error)
}

// Accounts exposes all queries in its generated store group.
type Accounts interface {
	AccountsReader
	AccountsWriter
}

type telemetryAccountsStore[SK any] struct {
	store  *meshStore[SK]
	target Accounts
}

func (q *telemetryAccountsStore[SK]) GetAccount(ctx context.Context, arg *GetAccountT, storeOptions ...QueryOption) (result *Account, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Accounts", "GetAccount", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetAccount(ctx, arg, storeOptions...)
}

func (q *telemetryAccountsStore[SK]) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameT, storeOptions ...QueryOption) (result *Account, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Accounts", "UpdateAccountName", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.UpdateAccountName(ctx, arg, storeOptions...)
}

func (q *telemetryAccountsStore[SK]) UpsertAccount(ctx context.Context, arg *UpsertAccountT, storeOptions ...QueryOption) (result *Account, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Accounts", "UpsertAccount", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.UpsertAccount(ctx, arg, storeOptions...)
}

// WithAccountsFactory configures an optional wrapper for the Accounts query group.
// A nil factory leaves the generated query group unwrapped.
func WithAccountsFactory(createAccounts func(Accounts) Accounts) StoreOption {
	return func(options *storeOptions) { options.factories.Accounts = createAccounts }
}

var _ Accounts = (*groupedMeshStore[uint8])(nil)
var _ Accounts = (*telemetryAccountsStore[uint8])(nil)

// Accounts returns the Accounts query group.
func (q *meshStore[SK]) Accounts() Accounts {
	return q.groups.Accounts
}

// GetAccount executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetAccount(ctx context.Context, arg *GetAccountT, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Accounts", "GetAccount", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetAccount(ctx, arg)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetAccount(ctx, arg)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetAccount(ctx, arg)
	}
}

// UpdateAccountName executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameT, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Accounts", "UpdateAccountName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.UpdateAccountName(ctx, arg)
}

// UpsertAccount executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpsertAccount(ctx context.Context, arg *UpsertAccountT, storeOptions ...QueryOption) (result *Account, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Accounts", "UpsertAccount", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.UpsertAccount(ctx, arg)
}
