// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	pgmesh "github.com/sundayfun/pgmesh"
)

// ReportsReader exposes read queries in the Reports store group.
type ReportsReader interface {
	// CountAccounts executes the generated CountAccounts query.
	CountAccounts(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (int64, error)
}

// ReportsWriter exposes write queries in the Reports store group.
type ReportsWriter interface {
}

// Reports exposes all queries in its generated store group.
type Reports interface {
	ReportsReader
	ReportsWriter
}

type telemetryReportsStore[SK any] struct {
	store  *meshStore[SK]
	target Reports
}

func (q *telemetryReportsStore[SK]) CountAccounts(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Reports", "CountAccounts", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.CountAccounts(ctx, tenantID, storeOptions...)
}

// WithReportsFactory configures an optional wrapper for the Reports query group.
// A nil factory leaves the generated query group unwrapped.
func WithReportsFactory(createReports func(Reports) Reports) StoreOption {
	return func(options *storeOptions) { options.factories.Reports = createReports }
}

var _ Reports = (*groupedMeshStore[uint8])(nil)
var _ Reports = (*telemetryReportsStore[uint8])(nil)

// Reports returns the Reports query group.
func (q *meshStore[SK]) Reports() Reports {
	return q.groups.Reports
}

// CountAccounts executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CountAccounts(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Reports", "CountAccounts", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(tenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).CountAccounts(ctx, tenantID)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().CountAccounts(ctx, tenantID)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().CountAccounts(ctx, tenantID)
	}
}
