// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	"database/sql"
	"errors"
	"github.com/jackc/pgx/v5"
)

// writeQueries exposes primary-capable generated queries.
type writeQueries struct {
	main    *Queries
	mirrors []*Queries
}

func newWriteQueries(q *Queries, mirrors ...*Queries) *writeQueries {
	return &writeQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *writeQueries) WithTx(tx pgx.Tx) *writeQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *writeQueries) WithMirrors(qs ...*writeQueries) *writeQueries {
	var mirrors []*Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *writeQueries) mirror(fn func(*Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// CopyAccounts executes the generated CopyAccounts query.
func (q *writeQueries) CopyAccounts(ctx context.Context, arg []*CopyAccountsParams) (int64, error) {
	rv0, err := q.main.CopyAccounts(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.CopyAccounts(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// UpdateAccountName executes the generated UpdateAccountName query.
func (q *writeQueries) UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error) {
	rv0, err := q.main.UpdateAccountName(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.UpdateAccountName(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// UpsertAccount executes the generated UpsertAccount query.
func (q *writeQueries) UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error) {
	rv0, err := q.main.UpsertAccount(ctx, arg)
	if err != nil {
		var zero0 *Account
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *Queries) error {
		_, err := mirror.UpsertAccount(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}
