// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sharded

import (
	"context"
)

type Querier interface {
	// kind: read
	// shard: tenantKey(tenant_id)
	// store: Reports
	CountAccounts(ctx context.Context, tenantID int64) (int64, error)
	// kind: read
	// shard: tenantKey(tenant_id)
	// store: Accounts
	GetAccount(ctx context.Context, arg *GetAccountParams) (*Account, error)
	// kind: write
	// shard: tenantKey(tenant_id)
	// store: Accounts
	UpdateAccountName(ctx context.Context, arg *UpdateAccountNameParams) (*Account, error)
	// kind: write
	// shard: tenantKey(tenant_id)
	// store: Accounts
	UpsertAccount(ctx context.Context, arg *UpsertAccountParams) (*Account, error)
}

var _ Querier = (*Queries)(nil)
