// Code generated by pgmesh. DO NOT EDIT.

package sharded

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	pgmesh "github.com/sundayfun/pgmesh"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
	"log/slog"
)

type queryOptions struct {
	primary bool
	tx      pgx.Tx
}

// QueryOption customizes routing for one generated query call.
type QueryOption func(*queryOptions)

// ReadFromPrimary routes a read query to the primary database.
func ReadFromPrimary() QueryOption {
	return func(options *queryOptions) { options.primary = true }
}

// WithTx executes a query through tx and suppresses write mirrors.
func WithTx(tx pgx.Tx) QueryOption {
	return func(options *queryOptions) { options.tx = tx }
}

func applyQueryOptions(options ...QueryOption) queryOptions {
	var result queryOptions
	for _, option := range options {
		if option != nil {
			option(&result)
		}
	}
	return result
}

type queryStore struct {
	*readQueries
	*writeQueries
}

func newQueryStore(q *Queries, mirrors ...*Queries) *queryStore {
	return &queryStore{
		readQueries:  newReadQueries(q),
		writeQueries: newWriteQueries(q, mirrors...),
	}
}

// WithTx returns a store wrapper that executes queries through tx.
func (q *queryStore) WithTx(tx pgx.Tx) *queryStore {
	return newQueryStore(q.writeQueries.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *queryStore) WithMirrors(qs ...*queryStore) *queryStore {
	var mirrors []*Queries
	mirrors = append(mirrors, q.writeQueries.mirrors...)
	for _, mirror := range qs {
		if mirror == nil || mirror.writeQueries == nil {
			continue
		}
		mirrors = append(mirrors, mirror.writeQueries.main)
		mirrors = append(mirrors, mirror.writeQueries.mirrors...)
	}
	return newQueryStore(q.writeQueries.main, mirrors...)
}

func newStoreNode(database DBTX) pgmesh.Node[*readQueries, *queryStore] {
	queries := New(database)
	return pgmesh.NewNode(newReadQueries(queries), newQueryStore(queries))
}

type storeOptions struct {
	tracerProvider trace.TracerProvider
	meterProvider  metric.MeterProvider
	logger         *slog.Logger
	factories      struct {
		Accounts func(Accounts) Accounts
		Reports  func(Reports) Reports
	}
}

// StoreOption customizes a generated store.
type StoreOption func(*storeOptions)

// WithTracerProvider configures the provider used for routed query spans.
// A nil provider uses the global OpenTelemetry tracer provider.
func WithTracerProvider(provider trace.TracerProvider) StoreOption {
	return func(options *storeOptions) { options.tracerProvider = provider }
}

// WithMeterProvider configures the provider used for routed query metrics.
// A nil provider uses the global OpenTelemetry meter provider.
func WithMeterProvider(provider metric.MeterProvider) StoreOption {
	return func(options *storeOptions) { options.meterProvider = provider }
}

// WithLogger configures optional structured logging for routed queries.
// A nil logger disables logging.
func WithLogger(logger *slog.Logger) StoreOption {
	return func(options *storeOptions) { options.logger = logger }
}

func applyStoreOptions(options ...StoreOption) (storeOptions, error) {
	var result storeOptions
	for index, option := range options {
		if option == nil {
			return storeOptions{}, fmt.Errorf("pgmesh: store option %d is nil", index)
		}
		option(&result)
	}
	return result, nil
}

// Topology is an opaque database topology for Store.
type Topology interface {
	buildStore(context.Context, storeOptions) (Store, error)
}

type singletonConfig struct {
	name     string
	primary  DBTX
	replicas []DBTX
	mirrors  []DBTX
}

// SingletonOption customizes a single-database topology.
type SingletonOption func(*singletonConfig)

// WithDatabaseName identifies the database in telemetry.
// An empty name defaults to "default".
func WithDatabaseName(name string) SingletonOption {
	return func(config *singletonConfig) { config.name = name }
}

// WithReadReplicas appends databases used for round-robin reads.
func WithReadReplicas(databases ...DBTX) SingletonOption {
	replicas := append([]DBTX(nil), databases...)
	return func(config *singletonConfig) { config.replicas = append(config.replicas, replicas...) }
}

// WithWriteMirrors appends databases that synchronously receive writes.
func WithWriteMirrors(databases ...DBTX) SingletonOption {
	mirrors := append([]DBTX(nil), databases...)
	return func(config *singletonConfig) { config.mirrors = append(config.mirrors, mirrors...) }
}

type singletonTopology struct {
	config singletonConfig
	err    error
}

// Singleton returns a topology with one primary database.
func Singleton(primary DBTX, options ...SingletonOption) Topology {
	config := singletonConfig{name: "default", primary: primary}
	for index, option := range options {
		if option == nil {
			return singletonTopology{err: fmt.Errorf("pgmesh: singleton option %d is nil", index)}
		}
		option(&config)
	}
	return singletonTopology{config: config}
}

// NewStore creates the generated query API from an opaque topology configuration.
func NewStore(ctx context.Context, topology Topology, options ...StoreOption) (Store, error) {
	if topology == nil {
		return nil, fmt.Errorf("pgmesh: topology is nil")
	}
	storeOptions, err := applyStoreOptions(options...)
	if err != nil {
		return nil, err
	}
	return topology.buildStore(ctx, storeOptions)
}

type meshStore[SK any] struct {
	mesh     *pgmesh.Mesh[*readQueries, *queryStore, SK]
	resolver ShardResolver[SK]
	groups   struct {
		Accounts Accounts
		Reports  Reports
	}
}

var _ Store = (*meshStore[uint8])(nil)

type groupedMeshStore[SK any] struct {
	store *meshStore[SK]
}

func (q *meshStore[SK]) initializeGroups(options storeOptions) {
	internalAccounts := &groupedMeshStore[SK]{store: q}
	q.groups.Accounts = internalAccounts
	if createAccounts := options.factories.Accounts; createAccounts != nil {
		q.groups.Accounts = &telemetryAccountsStore[SK]{store: q, target: createAccounts(internalAccounts)}
	}
	internalReports := &groupedMeshStore[SK]{store: q}
	q.groups.Reports = internalReports
	if createReports := options.factories.Reports; createReports != nil {
		q.groups.Reports = &telemetryReportsStore[SK]{store: q, target: createReports(internalReports)}
	}
}

func (c singletonTopology) buildStore(_ context.Context, options storeOptions) (Store, error) {
	if c.err != nil {
		return nil, c.err
	}
	config := c.config
	if config.name == "" {
		config.name = "default"
	}
	if config.primary == nil {
		return nil, fmt.Errorf("pgmesh: database primary is nil")
	}
	for index, database := range config.replicas {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database replica %d is nil", index)
		}
	}
	for index, database := range config.mirrors {
		if database == nil {
			return nil, fmt.Errorf("pgmesh: database mirror %d is nil", index)
		}
	}
	primary := newStoreNode(config.primary)
	replicas := make([]pgmesh.Node[*readQueries, *queryStore], 0, len(config.replicas))
	for _, database := range config.replicas {
		replicas = append(replicas, newStoreNode(database))
	}
	replicaSet := pgmesh.NewReplicaSet(config.name, primary, replicas)
	mirrors := make([]*queryStore, 0, len(config.mirrors))
	for _, database := range config.mirrors {
		mirrors = append(mirrors, newStoreNode(database).Writer())
	}
	replicaSet = replicaSet.WithWriteMirrors(mirrors...)
	mesh, err := pgmesh.NewBuilder[*readQueries, *queryStore, uint8](1).
		WithHasher(pgmesh.ConstantShardHashFor[uint8](0)).
		WithTracerProvider(options.tracerProvider).
		WithMeterProvider(options.meterProvider).
		WithLogger(options.logger).
		Link(0, replicaSet).
		Build()
	if err != nil {
		return nil, err
	}
	store := &meshStore[uint8]{mesh: mesh}
	store.initializeGroups(options)
	return store, nil
}
