// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	pgmesh "github.com/sundayfun/pgmesh"
	db "github.com/sundayfun/pgmesh/tests/generate/separate_package/internal"
	"reflect"
	"sync"
)

// CopyUsersT combines SQL and routing parameters for CopyUsers.
type CopyUsersT struct {
	TenantKey
	ID   int64
	Name string
}

func (arg *CopyUsersT) sqlcParams() *db.CopyUsersParams {
	return &db.CopyUsersParams{
		ID:       arg.ID,
		TenantID: arg.TenantKey.TenantID,
		Name:     arg.Name,
	}
}

// CreateUserT combines SQL and routing parameters for CreateUser.
type CreateUserT struct {
	TenantKey
	ID   int64
	Name string
}

func (arg *CreateUserT) sqlcParams() *db.CreateUserParams {
	return &db.CreateUserParams{
		ID:       arg.ID,
		TenantID: arg.TenantKey.TenantID,
		Name:     arg.Name,
	}
}

// GetUserT combines SQL and routing parameters for GetUser.
type GetUserT struct {
	TenantKey
	ID int64
}

func (arg *GetUserT) sqlcParams() *db.GetUserParams {
	return &db.GetUserParams{
		TenantID: arg.TenantKey.TenantID,
		ID:       arg.ID,
	}
}

// ListUsersByIDsT combines SQL and routing parameters for ListUsersByIDs.
type ListUsersByIDsT struct {
	TenantKey
	ID int64
}

// UpdateUserNameT combines SQL and routing parameters for UpdateUserName.
type UpdateUserNameT struct {
	TenantKey
	ID   int64
	Name string
}

func (arg *UpdateUserNameT) sqlcParams() *db.UpdateUserNameParams {
	return &db.UpdateUserNameParams{
		TenantID: arg.TenantKey.TenantID,
		ID:       arg.ID,
		Name:     arg.Name,
	}
}

type copyUsersBatchState struct {
	mu       sync.Mutex
	enabled  bool
	batchers map[string]*pgmesh.CopyBatcher[*db.CopyUsersParams]
}

// WithCopyUsersBatching enables asynchronous micro-batching for CopyUsers.
func WithCopyUsersBatching(config pgmesh.CopyBatchConfig) StoreOption {
	configured := config
	return func(options *storeOptions) { options.copyBatching.copyUsers = &configured }
}

// UsersReader exposes read queries in the Users store group.
type UsersReader interface {
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserT, storeOptions ...QueryOption) (*User, error)
	// ListAllUsers executes the generated ListAllUsers query.
	ListAllUsers(ctx context.Context, storeOptions ...QueryOption) ([]*User, error)
	// ListUsersByIDs executes the generated ListUsersByIDs query.
	ListUsersByIDs(ctx context.Context, arg []*ListUsersByIDsT, storeOptions ...QueryOption) ([]*User, error)
}

// UsersWriter exposes write queries in the Users store group.
type UsersWriter interface {
	// CopyUsers executes the generated CopyUsers query.
	CopyUsers(ctx context.Context, arg []*CopyUsersT, storeOptions ...QueryOption) (int64, error)
	// EnqueueCopyUsers accepts rows for asynchronous COPY.
	EnqueueCopyUsers(ctx context.Context, arg []*CopyUsersT) *pgmesh.Future[int64]
	// FlushCopyUsers drains asynchronous submissions accepted before its barrier.
	FlushCopyUsers(ctx context.Context) error
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserT, storeOptions ...QueryOption) (*User, error)
	// DeleteAllUsers executes the generated DeleteAllUsers query.
	DeleteAllUsers(ctx context.Context, storeOptions ...QueryOption) error
	// DeleteAllUsersByName executes the generated DeleteAllUsersByName query.
	DeleteAllUsersByName(ctx context.Context, name string, storeOptions ...QueryOption) (int64, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameT, storeOptions ...QueryOption) (*User, error)
}

// Users exposes all queries in its generated store group.
type Users interface {
	UsersReader
	UsersWriter
}

type telemetryUsersStore[SK any] struct {
	store  *meshStore[SK]
	target Users
}

func (q *telemetryUsersStore[SK]) CopyUsers(ctx context.Context, arg []*CopyUsersT, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "CopyUsers", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.CopyUsers(ctx, arg, storeOptions...)
}

func (q *telemetryUsersStore[SK]) EnqueueCopyUsers(ctx context.Context, arg []*CopyUsersT) *pgmesh.Future[int64] {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "EnqueueCopyUsers", pgmesh.QueryKindWrite)
	future := q.target.EnqueueCopyUsers(ctx, arg)
	return pgmesh.RunFuture(func() (int64, error) {
		count, err := future.Await(context.Background())
		storeSpan.End(err)
		return count, err
	})
}

func (q *telemetryUsersStore[SK]) FlushCopyUsers(ctx context.Context) error {
	return q.target.FlushCopyUsers(ctx)
}

func (q *telemetryUsersStore[SK]) CreateUser(ctx context.Context, arg *CreateUserT, storeOptions ...QueryOption) (result *User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "CreateUser", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.CreateUser(ctx, arg, storeOptions...)
}

func (q *telemetryUsersStore[SK]) DeleteAllUsers(ctx context.Context, storeOptions ...QueryOption) (err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "DeleteAllUsers", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteAllUsers(ctx, storeOptions...)
}

func (q *telemetryUsersStore[SK]) DeleteAllUsersByName(ctx context.Context, name string, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "DeleteAllUsersByName", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteAllUsersByName(ctx, name, storeOptions...)
}

func (q *telemetryUsersStore[SK]) GetUser(ctx context.Context, arg *GetUserT, storeOptions ...QueryOption) (result *User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "GetUser", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetUser(ctx, arg, storeOptions...)
}

func (q *telemetryUsersStore[SK]) ListAllUsers(ctx context.Context, storeOptions ...QueryOption) (result []*User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "ListAllUsers", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.ListAllUsers(ctx, storeOptions...)
}

func (q *telemetryUsersStore[SK]) ListUsersByIDs(ctx context.Context, arg []*ListUsersByIDsT, storeOptions ...QueryOption) (result []*User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "ListUsersByIDs", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.ListUsersByIDs(ctx, arg, storeOptions...)
}

func (q *telemetryUsersStore[SK]) UpdateUserName(ctx context.Context, arg *UpdateUserNameT, storeOptions ...QueryOption) (result *User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Users", "UpdateUserName", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.UpdateUserName(ctx, arg, storeOptions...)
}

// WithUsersFactory configures an optional wrapper for the Users query group.
// A nil factory leaves the generated query group unwrapped.
func WithUsersFactory(createUsers func(Users) Users) StoreOption {
	return func(options *storeOptions) { options.factories.Users = createUsers }
}

var _ Users = (*groupedMeshStore[uint8])(nil)
var _ Users = (*telemetryUsersStore[uint8])(nil)

// Users returns the Users query group.
func (q *meshStore[SK]) Users() Users {
	return q.groups.Users
}

// CopyUsers groups rows by physical shard and executes one copy per group.
func (q *groupedMeshStore[SK]) CopyUsers(ctx context.Context, arg []*CopyUsersT, storeOptions ...QueryOption) (result int64, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "CopyUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	type copyShardGroup struct {
		shard *pgmesh.Shard[*readQueries, *queryStore]
		args  []*db.CopyUsersParams
	}
	groupsByName := make(map[string]*copyShardGroup)
	for inputIndex, item := range arg {
		var shardKey SK
		if q.store.resolver != nil {
			shardKey = q.store.resolver.TenantKey(item.TenantKey)
		}
		shard, routeErr := q.store.mesh.Shard(shardKey)
		if routeErr != nil {
			err = fmt.Errorf("route CopyUsers input %d: %w", inputIndex, routeErr)
			return result, err
		}
		shardGroup := groupsByName[shard.Name()]
		if shardGroup == nil {
			shardGroup = &copyShardGroup{shard: shard, args: make([]*db.CopyUsersParams, 0)}
			groupsByName[shard.Name()] = shardGroup
		}
		shardGroup.args = append(shardGroup.args, item.sqlcParams())
	}

	groups := make([]*copyShardGroup, 0, len(groupsByName))
	for _, shard := range q.store.mesh.AllShards() {
		if shardGroup := groupsByName[shard.Name()]; shardGroup != nil {
			groups = append(groups, shardGroup)
		}
	}
	if options.tx != nil && len(groups) > 1 {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction, len(groups))
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		mode = pgmesh.RouteModeTransaction
	}
	querySpan.SetMultiRoute(mode, len(groups))
	if len(groups) == 0 {
		return result, err
	}

	type copyResult struct {
		count int64
		err   error
	}
	copyResults := make([]copyResult, len(groups))
	var waitGroup sync.WaitGroup
	for index, shardGroup := range groups {
		waitGroup.Go(func() {
			route := shardGroup.shard.WriteRoute()
			target := route.Target
			if options.tx != nil {
				target = target.WithTx(options.tx)
			}
			queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
			copyResults[index].count, copyResults[index].err = target.CopyUsers(queryCtx, shardGroup.args)
			physicalQuerySpan.End(copyResults[index].err)
		})
	}
	waitGroup.Wait()

	copyErrors := make([]error, 0, len(groups))
	for index, copyResult := range copyResults {
		if copyResult.err != nil {
			copyErrors = append(copyErrors, fmt.Errorf("query CopyUsers on replica set %q: %w", groups[index].shard.Name(), copyResult.err))
		}
	}
	err = errors.Join(copyErrors...)
	if err != nil {
		return result, err
	}
	for _, copyResult := range copyResults {
		result += copyResult.count
	}
	return result, err
}

// EnqueueCopyUsers accepts rows for asynchronous COPY.
func (q *groupedMeshStore[SK]) EnqueueCopyUsers(ctx context.Context, arg []*CopyUsersT) *pgmesh.Future[int64] {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "EnqueueCopyUsers", pgmesh.QueryKindWrite)
	finish := func(future *pgmesh.Future[int64]) *pgmesh.Future[int64] {
		return pgmesh.RunFuture(func() (int64, error) {
			count, err := future.Await(context.Background())
			querySpan.End(err)
			return count, err
		})
	}

	type asyncCopyShardGroup struct {
		shard   *pgmesh.Shard[*readQueries, *queryStore]
		args    []*db.CopyUsersParams
		batcher *pgmesh.CopyBatcher[*db.CopyUsersParams]
	}
	groupsByName := make(map[string]*asyncCopyShardGroup)
	for inputIndex, item := range arg {
		var shardKey SK
		if q.store.resolver != nil {
			shardKey = q.store.resolver.TenantKey(item.TenantKey)
		}
		shard, routeErr := q.store.mesh.Shard(shardKey)
		if routeErr != nil {
			err := fmt.Errorf("route EnqueueCopyUsers input %d: %w", inputIndex, routeErr)
			return finish(pgmesh.ResolvedFuture[int64](0, err))
		}
		shardGroup := groupsByName[shard.Name()]
		if shardGroup == nil {
			shardGroup = &asyncCopyShardGroup{shard: shard, args: make([]*db.CopyUsersParams, 0)}
			groupsByName[shard.Name()] = shardGroup
		}
		shardGroup.args = append(shardGroup.args, item.sqlcParams())
	}
	groups := make([]*asyncCopyShardGroup, 0, len(groupsByName))
	for _, shard := range q.store.mesh.AllShards() {
		if shardGroup := groupsByName[shard.Name()]; shardGroup != nil {
			groups = append(groups, shardGroup)
		}
	}
	querySpan.SetMultiRoute(pgmesh.RouteModePrimary, len(groups))
	if len(groups) == 0 {
		return finish(pgmesh.ResolvedFuture[int64](0, nil))
	}
	state := q.store.copyUsersBatch
	state.mu.Lock()
	if err := ctx.Err(); err != nil {
		state.mu.Unlock()
		return finish(pgmesh.ResolvedFuture[int64](0, err))
	}
	for _, shardGroup := range groups {
		shardGroup.batcher = state.batchers[shardGroup.shard.Name()]
		if shardGroup.batcher == nil {
			state.mu.Unlock()
			err := fmt.Errorf("query EnqueueCopyUsers has no copy batcher for replica set %q", shardGroup.shard.Name())
			return finish(pgmesh.ResolvedFuture[int64](0, err))
		}
	}
	acceptedContext := context.WithoutCancel(ctx)
	type asyncCopyResult struct {
		shardName string
		future    *pgmesh.Future[int64]
	}
	asyncResults := make([]asyncCopyResult, 0, len(groups))
	for _, shardGroup := range groups {
		var future *pgmesh.Future[int64]
		if state.enabled {
			future = shardGroup.batcher.Submit(acceptedContext, shardGroup.args)
		} else {
			future = shardGroup.batcher.SubmitImmediate(acceptedContext, shardGroup.args)
		}
		asyncResults = append(asyncResults, asyncCopyResult{shardName: shardGroup.shard.Name(), future: future})
	}
	state.mu.Unlock()

	combined := pgmesh.RunFuture(func() (int64, error) {
		var count int64
		copyErrors := make([]error, 0, len(asyncResults))
		for _, asyncResult := range asyncResults {
			shardCount, err := asyncResult.future.Await(context.Background())
			if err != nil {
				copyErrors = append(copyErrors, fmt.Errorf("query CopyUsers on replica set %q: %w", asyncResult.shardName, err))
				continue
			}
			count += shardCount
		}
		if err := errors.Join(copyErrors...); err != nil {
			return 0, err
		}
		return count, nil
	})
	return finish(combined)
}

// FlushCopyUsers drains asynchronous submissions accepted before its barrier.
func (q *groupedMeshStore[SK]) FlushCopyUsers(ctx context.Context) error {
	state := q.store.copyUsersBatch
	state.mu.Lock()
	type copyFlushResult struct {
		shardName string
		future    *pgmesh.Future[struct{}]
	}
	flushes := make([]copyFlushResult, 0, len(q.store.mesh.AllShards()))
	for _, shard := range q.store.mesh.AllShards() {
		if batcher := state.batchers[shard.Name()]; batcher != nil {
			flushes = append(flushes, copyFlushResult{shardName: shard.Name(), future: batcher.FlushAsync()})
		}
	}
	state.mu.Unlock()
	flushErrors := make([]error, 0, len(flushes))
	for _, flushResult := range flushes {
		if _, err := flushResult.future.Await(ctx); err != nil {
			flushErrors = append(flushErrors, fmt.Errorf("flush CopyUsers on replica set %q: %w", flushResult.shardName, err))
			if ctx.Err() != nil {
				break
			}
		}
	}
	return errors.Join(flushErrors...)
}

// CreateUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CreateUser(ctx context.Context, arg *CreateUserT, storeOptions ...QueryOption) (result *db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "CreateUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.TenantKey(arg.TenantKey)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode)
	ctx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.CreateUser(ctx, arg.sqlcParams())
}

// DeleteAllUsers executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) DeleteAllUsers(ctx context.Context, storeOptions ...QueryOption) (err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "DeleteAllUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction, len(shards))
		err = pgmesh.ErrCrossShardTransaction
		return err
	}

	mode := pgmesh.RouteModePrimary
	querySpan.SetMultiRoute(mode, len(shards))

	type shardResult struct {
		err error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			route := shard.WriteRoute()
			queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
			shardResults[index].err = route.Target.DeleteAllUsers(queryCtx)
			physicalQuerySpan.End(shardResults[index].err)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query DeleteAllUsers on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return err
	}
	return err
}

// DeleteAllUsersByName executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) DeleteAllUsersByName(ctx context.Context, name string, storeOptions ...QueryOption) (result int64, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "DeleteAllUsersByName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction, len(shards))
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModePrimary
	querySpan.SetMultiRoute(mode, len(shards))

	type shardResult struct {
		value int64
		err   error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			route := shard.WriteRoute()
			queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
			shardResults[index].value, shardResults[index].err = route.Target.DeleteAllUsersByName(queryCtx, name)
			physicalQuerySpan.End(shardResults[index].err)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query DeleteAllUsersByName on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return result, err
	}
	for _, shardResult := range shardResults {
		result += shardResult.value
	}
	return result, err
}

// GetUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetUser(ctx context.Context, arg *GetUserT, storeOptions ...QueryOption) (result *db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "GetUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.TenantKey(arg.TenantKey)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(pgmesh.RouteModeTransaction)
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		ctx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeTransaction)
		defer func() { physicalQuerySpan.End(err) }()
		return target.GetUser(ctx, arg.sqlcParams())

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(pgmesh.RouteModePrimary)
		route := shard.WriteRoute()
		ctx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata(), pgmesh.RouteModePrimary)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.GetUser(ctx, arg.sqlcParams())

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(pgmesh.RouteModeRead)
		route := shard.ReadRoute()
		ctx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeRead)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.GetUser(ctx, arg.sqlcParams())
	}
}

// ListAllUsers executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) ListAllUsers(ctx context.Context, storeOptions ...QueryOption) (result []*db.User, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "ListAllUsers", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction, len(shards))
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModeRead
	if options.primary {
		mode = pgmesh.RouteModePrimary
	}
	querySpan.SetMultiRoute(mode, len(shards))

	type shardResult struct {
		value []*db.User
		err   error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			if options.primary {
				route := shard.WriteRoute()
				queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
				shardResults[index].value, shardResults[index].err = route.Target.ListAllUsers(queryCtx)
				physicalQuerySpan.End(shardResults[index].err)
				return
			}
			route := shard.ReadRoute()
			queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
			shardResults[index].value, shardResults[index].err = route.Target.ListAllUsers(queryCtx)
			physicalQuerySpan.End(shardResults[index].err)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query ListAllUsers on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return result, err
	}
	for _, shardResult := range shardResults {
		result = append(result, shardResult.value...)
	}
	return result, err
}

// ListUsersByIDs groups lookup values by physical shard and restores input-key result order.
func (q *groupedMeshStore[SK]) ListUsersByIDs(ctx context.Context, arg []*ListUsersByIDsT, storeOptions ...QueryOption) (result []*db.User, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "ListUsersByIDs", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	type manyShardGroup struct {
		shard     *pgmesh.Shard[*readQueries, *queryStore]
		args      []int64
		requested map[any]struct{}
	}
	type manyOrderItem struct {
		shardName string
		key       any
	}
	groupsByName := make(map[string]*manyShardGroup)
	orderedItems := make([]manyOrderItem, 0)
	for inputIndex, item := range arg {
		if item == nil {
			err = fmt.Errorf("route ListUsersByIDs input %d: shard parameter is nil", inputIndex)
			return result, err
		}
		lookupValue := item.ID
		lookupKey := any(lookupValue)
		if lookupKey != nil && !reflect.ValueOf(lookupKey).Comparable() {
			err = fmt.Errorf("route ListUsersByIDs input %d: lookup key type %T is not comparable", inputIndex, lookupKey)
			return result, err
		}
		var shardKey SK
		if q.store.resolver != nil {
			shardKey = q.store.resolver.TenantKey(item.TenantKey)
		}
		shard, routeErr := q.store.mesh.Shard(shardKey)
		if routeErr != nil {
			err = fmt.Errorf("route ListUsersByIDs input %d: %w", inputIndex, routeErr)
			return result, err
		}
		shardGroup := groupsByName[shard.Name()]
		if shardGroup == nil {
			shardGroup = &manyShardGroup{shard: shard, args: make([]int64, 0), requested: make(map[any]struct{})}
			groupsByName[shard.Name()] = shardGroup
		}
		if _, exists := shardGroup.requested[lookupKey]; exists {
			continue
		}
		shardGroup.requested[lookupKey] = struct{}{}
		shardGroup.args = append(shardGroup.args, lookupValue)
		orderedItems = append(orderedItems, manyOrderItem{shardName: shard.Name(), key: lookupKey})
	}

	groups := make([]*manyShardGroup, 0, len(groupsByName))
	for _, shard := range q.store.mesh.AllShards() {
		if shardGroup := groupsByName[shard.Name()]; shardGroup != nil {
			groups = append(groups, shardGroup)
		}
	}
	if options.tx != nil && len(groups) > 1 {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction, len(groups))
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModeRead
	if options.primary {
		mode = pgmesh.RouteModePrimary
	}
	if options.tx != nil {
		mode = pgmesh.RouteModeTransaction
	}
	querySpan.SetMultiRoute(mode, len(groups))
	if len(groups) == 0 {
		return result, err
	}

	type manyResult struct {
		value []*db.User
		err   error
	}
	groupResults := make([]manyResult, len(groups))
	var waitGroup sync.WaitGroup
	for index, shardGroup := range groups {
		waitGroup.Go(func() {
			switch {
			case options.tx != nil:
				route := shardGroup.shard.WriteRoute()
				target := route.Target.WithTx(options.tx)
				queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
				groupResults[index].value, groupResults[index].err = target.ListUsersByIDs(queryCtx, shardGroup.args)
				physicalQuerySpan.End(groupResults[index].err)
			case options.primary:
				route := shardGroup.shard.WriteRoute()
				queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
				groupResults[index].value, groupResults[index].err = route.Target.ListUsersByIDs(queryCtx, shardGroup.args)
				physicalQuerySpan.End(groupResults[index].err)
			default:
				route := shardGroup.shard.ReadRoute()
				queryCtx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata().WithoutVirtualShard(), mode)
				groupResults[index].value, groupResults[index].err = route.Target.ListUsersByIDs(queryCtx, shardGroup.args)
				physicalQuerySpan.End(groupResults[index].err)
			}
		})
	}
	waitGroup.Wait()

	groupErrors := make([]error, 0, len(groups))
	for index, groupResult := range groupResults {
		if groupResult.err != nil {
			groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByIDs on replica set %q: %w", groups[index].shard.Name(), groupResult.err))
		}
	}
	err = errors.Join(groupErrors...)
	if err != nil {
		return result, err
	}

	rowsByGroup := make(map[string]map[any][]*db.User, len(groups))
	for groupIndex, groupResult := range groupResults {
		rowsByKey := make(map[any][]*db.User)
		rowsByGroup[groups[groupIndex].shard.Name()] = rowsByKey
		for resultIndex, row := range groupResult.value {
			if row == nil {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByIDs on replica set %q returned nil row at result %d", groups[groupIndex].shard.Name(), resultIndex))
				continue
			}
			resultKey := any(row.ID)
			if resultKey != nil && !reflect.ValueOf(resultKey).Comparable() {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByIDs on replica set %q result %d has non-comparable lookup key type %T", groups[groupIndex].shard.Name(), resultIndex, resultKey))
				continue
			}
			if _, requested := groups[groupIndex].requested[resultKey]; !requested {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByIDs on replica set %q result %d has an unrequested lookup key", groups[groupIndex].shard.Name(), resultIndex))
				continue
			}
			rowsByKey[resultKey] = append(rowsByKey[resultKey], row)
		}
	}
	err = errors.Join(groupErrors...)
	if err != nil {
		return result, err
	}

	for _, orderedItem := range orderedItems {
		result = append(result, rowsByGroup[orderedItem.shardName][orderedItem.key]...)
	}
	return result, err
}

// UpdateUserName executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpdateUserName(ctx context.Context, arg *UpdateUserNameT, storeOptions ...QueryOption) (result *db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "UpdateUserName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.TenantKey(arg.TenantKey)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode)
	ctx, physicalQuerySpan := querySpan.StartQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.UpdateUserName(ctx, arg.sqlcParams())
}
