// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"github.com/jackc/pgx/v5"
	db "github.com/sundayfun/pgmesh/tests/generate/separate_package/internal"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *db.Queries
}

func newReadQueries(q *db.Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAnalysis executes the generated GetAnalysis query.
func (q *readQueries) GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error) {
	rv0, err := q.main.GetAnalysis(ctx, arg)
	if err != nil {
		var zero0 *db.Analysis
		return zero0, err
	}
	return rv0, nil
}

// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
func (q *readQueries) GetTenantUserAnalysis(ctx context.Context, arg *db.GetTenantUserAnalysisParams) (*db.GetTenantUserAnalysisRow, error) {
	rv0, err := q.main.GetTenantUserAnalysis(ctx, arg)
	if err != nil {
		var zero0 *db.GetTenantUserAnalysisRow
		return zero0, err
	}
	return rv0, nil
}

// GetUser executes the generated GetUser query.
func (q *readQueries) GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error) {
	rv0, err := q.main.GetUser(ctx, arg)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	return rv0, nil
}

// ListAllUsers executes the generated ListAllUsers query.
func (q *readQueries) ListAllUsers(ctx context.Context) ([]*db.User, error) {
	rv0, err := q.main.ListAllUsers(ctx)
	if err != nil {
		var zero0 []*db.User
		return zero0, err
	}
	return rv0, nil
}

// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
func (q *readQueries) ListP2PMessageIDsByChat(ctx context.Context, arg *db.ListP2PMessageIDsByChatParams) ([]interface{}, error) {
	rv0, err := q.main.ListP2PMessageIDsByChat(ctx, arg)
	if err != nil {
		var zero0 []interface{}
		return zero0, err
	}
	return rv0, nil
}

// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
func (q *readQueries) ListP2PMessagesByChat(ctx context.Context, arg *db.ListP2PMessagesByChatParams) ([]*db.Message, error) {
	rv0, err := q.main.ListP2PMessagesByChat(ctx, arg)
	if err != nil {
		var zero0 []*db.Message
		return zero0, err
	}
	return rv0, nil
}

// ListUsersByIDs executes the generated ListUsersByIDs query.
func (q *readQueries) ListUsersByIDs(ctx context.Context, ids []int64) ([]*db.User, error) {
	rv0, err := q.main.ListUsersByIDs(ctx, ids)
	if err != nil {
		var zero0 []*db.User
		return zero0, err
	}
	return rv0, nil
}
