// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"fmt"
	pgmesh "github.com/sundayfun/pgmesh"
	db "github.com/sundayfun/pgmesh/tests/generate/separate_package/internal"
)

type shardDatabase struct {
	name     string
	primary  db.DBTX
	replicas []db.DBTX
}

type shardMapping struct {
	mainReplicaSet    string
	vshards           []uint64
	mirrorReplicaSets []string
}

type shardedOptions struct {
	replicaSets []shardDatabase
	mappings    []shardMapping
}

// ShardedOption customizes a sharded topology.
type ShardedOption func(*shardedOptions)

// WithReplicaSet appends a named primary and its optional read replicas.
func WithReplicaSet(name string, primary db.DBTX, replicas ...db.DBTX) ShardedOption {
	configuredReplicas := append([]db.DBTX(nil), replicas...)
	return func(options *shardedOptions) {
		options.replicaSets = append(options.replicaSets, shardDatabase{
			name: name, primary: primary, replicas: append([]db.DBTX(nil), configuredReplicas...),
		})
	}
}

// WithVShardMapping maps virtual shards to a main replica set and optional ordered write mirrors.
func WithVShardMapping(mainReplicaSet string, vshards []uint64, mirrorReplicaSets ...string) ShardedOption {
	configuredVShards := append([]uint64(nil), vshards...)
	configuredMirrors := append([]string(nil), mirrorReplicaSets...)
	return func(options *shardedOptions) {
		options.mappings = append(options.mappings, shardMapping{
			mainReplicaSet:    mainReplicaSet,
			vshards:           append([]uint64(nil), configuredVShards...),
			mirrorReplicaSets: append([]string(nil), configuredMirrors...),
		})
	}
}

type shardedTopology[SK any] struct {
	numVShards  uint64
	shardHasher pgmesh.ShardHasher[SK]
	resolver    ShardResolver[SK]
	options     shardedOptions
	err         error
}

// Sharded returns an opaque sharded topology.
func Sharded[SK any](numVShards uint64, shardHasher pgmesh.ShardHasher[SK], resolver ShardResolver[SK], options ...ShardedOption) Topology {
	var configured shardedOptions
	for index, option := range options {
		if option == nil {
			return shardedTopology[SK]{err: fmt.Errorf("pgmesh: sharded option %d is nil", index)}
		}
		option(&configured)
	}
	return shardedTopology[SK]{
		numVShards:  numVShards,
		shardHasher: shardHasher,
		resolver:    resolver,
		options:     configured,
	}
}

func (c shardedTopology[SK]) buildStore(ctx context.Context, options storeOptions) (Store, error) {
	if c.err != nil {
		return nil, c.err
	}
	if c.resolver == nil {
		return nil, fmt.Errorf("pgmesh: shard resolver is nil")
	}
	nodes := make(map[string]db.DBTX)
	meshOptions := make([]pgmesh.MeshOption, 0, len(c.options.replicaSets)+len(c.options.mappings)+3)
	for setIndex, set := range c.options.replicaSets {
		primaryDSN := fmt.Sprintf("pgmesh-internal://%d/primary", setIndex)
		nodes[primaryDSN] = set.primary
		replicaDSNs := make([]string, 0, len(set.replicas))
		for replicaIndex, database := range set.replicas {
			dsn := fmt.Sprintf("pgmesh-internal://%d/replica/%d", setIndex, replicaIndex)
			nodes[dsn] = database
			replicaDSNs = append(replicaDSNs, dsn)
		}
		meshOptions = append(meshOptions, pgmesh.WithReplicaSet(set.name, primaryDSN, replicaDSNs...))
	}
	for _, mapping := range c.options.mappings {
		meshOptions = append(meshOptions, pgmesh.WithVShardMapping(
			mapping.mainReplicaSet,
			mapping.vshards,
			mapping.mirrorReplicaSets...,
		))
	}
	meshOptions = append(meshOptions,
		pgmesh.WithTracerProvider(options.tracerProvider),
		pgmesh.WithMeterProvider(options.meterProvider),
		pgmesh.WithLogger(options.logger),
	)
	mesh, err := pgmesh.CreateMesh(ctx, c.numVShards,
		func(_ context.Context, dsn string) (pgmesh.Node[*readQueries, *queryStore], error) {
			database, ok := nodes[dsn]
			if !ok || database == nil {
				return pgmesh.Node[*readQueries, *queryStore]{}, fmt.Errorf("pgmesh: database node %q is nil", dsn)
			}
			return newStoreNode(database), nil
		},
		c.shardHasher,
		meshOptions...,
	)
	if err != nil {
		return nil, err
	}
	store := &meshStore[SK]{mesh: mesh, resolver: c.resolver}
	store.initializeGroups(options)
	return store, nil
}
