// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"github.com/jackc/pgx/v5/pgtype"
	pgmesh "github.com/sundayfun/pgmesh"
	db "github.com/sundayfun/pgmesh/tests/generate/separate_package/internal"
)

// ListP2PMessageIDsByChatT combines SQL and routing parameters for ListP2PMessageIDsByChat.
type ListP2PMessageIDsByChatT struct {
	Limit           int32
	UserID          int64
	PeerID          int64
	CreatedSince    pgtype.Timestamptz
	LastID          interface{}
	ToUserOrGroupID int64
	InGroup         bool
}

func (arg *ListP2PMessageIDsByChatT) sqlcParams() *db.ListP2PMessageIDsByChatParams {
	return &db.ListP2PMessageIDsByChatParams{
		Limit:        arg.Limit,
		UserID:       arg.UserID,
		PeerID:       arg.PeerID,
		CreatedSince: arg.CreatedSince,
		LastID:       arg.LastID,
	}
}

// ListP2PMessagesByChatT combines SQL and routing parameters for ListP2PMessagesByChat.
type ListP2PMessagesByChatT struct {
	Limit           int32
	UserID          int64
	PeerID          int64
	CreatedSince    pgtype.Timestamptz
	LastID          interface{}
	ToUserOrGroupID int64
	InGroup         bool
}

func (arg *ListP2PMessagesByChatT) sqlcParams() *db.ListP2PMessagesByChatParams {
	return &db.ListP2PMessagesByChatParams{
		Limit:        arg.Limit,
		UserID:       arg.UserID,
		PeerID:       arg.PeerID,
		CreatedSince: arg.CreatedSince,
		LastID:       arg.LastID,
	}
}

// QueryMessageReader exposes read queries in the QueryMessage store group.
type QueryMessageReader interface {
	// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
	ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatT, storeOptions ...QueryOption) ([]interface{}, error)
	// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
	ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatT, storeOptions ...QueryOption) ([]*Message, error)
}

// QueryMessageWriter exposes write queries in the QueryMessage store group.
type QueryMessageWriter interface {
}

// QueryMessage exposes all queries in its generated store group.
type QueryMessage interface {
	QueryMessageReader
	QueryMessageWriter
}

var _ QueryMessage = (*groupedMeshStore[uint8])(nil)

// QueryMessage returns the QueryMessage query group.
func (q *meshStore[SK]) QueryMessage() QueryMessage {
	return &groupedMeshStore[SK]{store: q}
}

// ListP2PMessageIDsByChat executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatT, storeOptions ...QueryOption) (result []interface{}, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "QueryMessage", "ListP2PMessageIDsByChat", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.MessageKey(arg.UserID, arg.ToUserOrGroupID, arg.InGroup)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).ListP2PMessageIDsByChat(ctx, arg.sqlcParams())

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().ListP2PMessageIDsByChat(ctx, arg.sqlcParams())

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().ListP2PMessageIDsByChat(ctx, arg.sqlcParams())
	}
}

// ListP2PMessagesByChat executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatT, storeOptions ...QueryOption) (result []*db.Message, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "QueryMessage", "ListP2PMessagesByChat", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.MessageKey(arg.UserID, arg.ToUserOrGroupID, arg.InGroup)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).ListP2PMessagesByChat(ctx, arg.sqlcParams())

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().ListP2PMessagesByChat(ctx, arg.sqlcParams())

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().ListP2PMessagesByChat(ctx, arg.sqlcParams())
	}
}
