// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	db "github.com/sundayfun/pgmesh/tests/generate/separate_package/internal"
)

// Analysis re-exports Analysis from the sqlc package.
type Analysis = db.Analysis

// AnalysisState re-exports AnalysisState from the sqlc package.
type AnalysisState = db.AnalysisState

// CopyUsersParams re-exports CopyUsersParams from the sqlc package.
type CopyUsersParams = db.CopyUsersParams

// CreateUserParams re-exports CreateUserParams from the sqlc package.
type CreateUserParams = db.CreateUserParams

// GetAnalysisParams re-exports GetAnalysisParams from the sqlc package.
type GetAnalysisParams = db.GetAnalysisParams

// GetTenantUserAnalysisParams re-exports GetTenantUserAnalysisParams from the sqlc package.
type GetTenantUserAnalysisParams = db.GetTenantUserAnalysisParams

// GetTenantUserAnalysisRow re-exports GetTenantUserAnalysisRow from the sqlc package.
type GetTenantUserAnalysisRow = db.GetTenantUserAnalysisRow

// GetUserParams re-exports GetUserParams from the sqlc package.
type GetUserParams = db.GetUserParams

// ListP2PMessageIDsByChatParams re-exports ListP2PMessageIDsByChatParams from the sqlc package.
type ListP2PMessageIDsByChatParams = db.ListP2PMessageIDsByChatParams

// ListP2PMessagesByChatParams re-exports ListP2PMessagesByChatParams from the sqlc package.
type ListP2PMessagesByChatParams = db.ListP2PMessagesByChatParams

// Message re-exports Message from the sqlc package.
type Message = db.Message

// NullAnalysisState re-exports NullAnalysisState from the sqlc package.
type NullAnalysisState = db.NullAnalysisState

// UpdateUserNameParams re-exports UpdateUserNameParams from the sqlc package.
type UpdateUserNameParams = db.UpdateUserNameParams

// User re-exports User from the sqlc package.
type User = db.User

// readQuerier exposes generated read queries.
type readQuerier interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *db.GetAnalysisParams) (*db.Analysis, error)
	// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
	GetTenantUserAnalysis(ctx context.Context, arg *db.GetTenantUserAnalysisParams) (*db.GetTenantUserAnalysisRow, error)
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *db.GetUserParams) (*db.User, error)
	// ListAllUsers executes the generated ListAllUsers query.
	ListAllUsers(ctx context.Context) ([]*db.User, error)
	// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
	ListP2PMessageIDsByChat(ctx context.Context, arg *db.ListP2PMessageIDsByChatParams) ([]interface{}, error)
	// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
	ListP2PMessagesByChat(ctx context.Context, arg *db.ListP2PMessagesByChatParams) ([]*db.Message, error)
	// ListUsersByID executes the generated ListUsersByID query.
	ListUsersByID(ctx context.Context, id []int64) ([]*db.User, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// CopyUsers executes the generated CopyUsers query.
	CopyUsers(ctx context.Context, arg []*db.CopyUsersParams) (int64, error)
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *db.CreateUserParams) (*db.User, error)
	// DeleteAllUsers executes the generated DeleteAllUsers query.
	DeleteAllUsers(ctx context.Context) error
	// DeleteAllUsersByName executes the generated DeleteAllUsersByName query.
	DeleteAllUsersByName(ctx context.Context, name string) (int64, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *db.UpdateUserNameParams) (*db.User, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// Analyses returns the Analyses query group.
	Analyses() Analyses
	// QueryMessage returns the QueryMessage query group.
	QueryMessage() QueryMessage
	// Users returns the Users query group.
	Users() Users
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ db.Querier = (*queryStore)(nil)

// ShardResolver resolves generated query parameters to shard keys.
type ShardResolver[SK any] interface {
	// MessageKey resolves the "messageKey" shard route.
	MessageKey(userID int64, toUserOrGroupID int64, inGroup bool) SK
	// Tenant resolves the "tenant" shard route.
	Tenant(tenantID int64) SK
}
