// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"github.com/jackc/pgx/v5/pgconn"
	pgmesh "github.com/sundayfun/pgmesh"
	db "github.com/sundayfun/pgmesh/tests/generate/commands/internal"
)

// BatchInsertCommandUsersT is the store parameter type for BatchInsertCommandUsers.
type BatchInsertCommandUsersT = db.BatchInsertCommandUsersParams

// CopyCommandUsersT is the store parameter type for CopyCommandUsers.
type CopyCommandUsersT = db.CopyCommandUsersParams

// CommandsReader exposes read queries in the Commands store group.
type CommandsReader interface {
	// BatchGetCommandUser executes the generated BatchGetCommandUser query.
	BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults
	// BatchListCommandUsersByTenant executes the generated BatchListCommandUsersByTenant query.
	BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults
	// GetCommandUser executes the generated GetCommandUser query.
	GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (*db.User, error)
	// ListCommandUsers executes the generated ListCommandUsers query.
	ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) ([]*db.User, error)
}

// CommandsWriter exposes write queries in the Commands store group.
type CommandsWriter interface {
	// BatchInsertCommandUsers executes the generated BatchInsertCommandUsers query.
	BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults
	// CopyCommandUsers executes the generated CopyCommandUsers query.
	CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (int64, error)
	// DeleteCommandUser executes the generated DeleteCommandUser query.
	DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) error
	// DeleteCommandUsersByTenant executes the generated DeleteCommandUsersByTenant query.
	DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (int64, error)
	// TouchCommandUser executes the generated TouchCommandUser query.
	TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (pgconn.CommandTag, error)
}

// Commands exposes all queries in its generated store group.
type Commands interface {
	CommandsReader
	CommandsWriter
}

type telemetryCommandsStore[SK any] struct {
	store  *meshStore[SK]
	target Commands
}

func (q *telemetryCommandsStore[SK]) BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults {
	return q.target.BatchGetCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults {
	return q.target.BatchInsertCommandUsers(ctx, arg, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults {
	return q.target.BatchListCommandUsersByTenant(ctx, tenantID, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "CopyCommandUsers", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.CopyCommandUsers(ctx, arg, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "DeleteCommandUser", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "DeleteCommandUsersByTenant", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteCommandUsersByTenant(ctx, tenantID, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result *db.User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "GetCommandUser", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) (result []*db.User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "ListCommandUsers", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.ListCommandUsers(ctx, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result pgconn.CommandTag, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Commands", "TouchCommandUser", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.TouchCommandUser(ctx, id, storeOptions...)
}

// WithCommandsFactory configures an optional wrapper for the Commands query group.
// A nil factory leaves the generated query group unwrapped.
func WithCommandsFactory(createCommands func(Commands) Commands) StoreOption {
	return func(options *storeOptions) { options.factories.Commands = createCommands }
}

var _ Commands = (*groupedMeshStore[uint8])(nil)
var _ Commands = (*telemetryCommandsStore[uint8])(nil)

// Commands returns the Commands query group.
func (q *meshStore[SK]) Commands() Commands {
	return q.groups.Commands
}

// BatchGetCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Shard(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		return shard.Write().WithTx(options.tx).BatchGetCommandUser(ctx, id)

	// Explicit primary reads bypass replicas.
	case options.primary:
		return shard.Write().BatchGetCommandUser(ctx, id)

	// Ordinary reads use the shard's replica route.
	default:
		return shard.Read().BatchGetCommandUser(ctx, id)
	}
}

// BatchInsertCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Shard(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	if options.tx != nil {
		target = target.WithTx(options.tx)
	}

	// Execute the write on the selected target.
	return target.BatchInsertCommandUsers(ctx, arg)
}

// BatchListCommandUsersByTenant executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Shard(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		return shard.Write().WithTx(options.tx).BatchListCommandUsersByTenant(ctx, tenantID)

	// Explicit primary reads bypass replicas.
	case options.primary:
		return shard.Write().BatchListCommandUsersByTenant(ctx, tenantID)

	// Ordinary reads use the shard's replica route.
	default:
		return shard.Read().BatchListCommandUsersByTenant(ctx, tenantID)
	}
}

// CopyCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "CopyCommandUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.CopyCommandUsers(ctx, arg)
}

// DeleteCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "DeleteCommandUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.DeleteCommandUser(ctx, id)
}

// DeleteCommandUsersByTenant executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "DeleteCommandUsersByTenant", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.DeleteCommandUsersByTenant(ctx, tenantID)
}

// GetCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result *db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "GetCommandUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetCommandUser(ctx, id)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetCommandUser(ctx, id)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetCommandUser(ctx, id)
	}
}

// ListCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) (result []*db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "ListCommandUsers", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).ListCommandUsers(ctx)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().ListCommandUsers(ctx)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().ListCommandUsers(ctx)
	}
}

// TouchCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result pgconn.CommandTag, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Commands", "TouchCommandUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.TouchCommandUser(ctx, id)
}
