package sqlcplugin

import (
	"context"
	"fmt"

	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

const (
	defaultOutputFileName = "store_querier.go"
	defaultPackageName    = "db"
	defaultSQLPackage     = "pgx/v5"
	defaultSQLQualifier   = "sql"
	defaultDatabaseSQL    = "database/sql"
	defaultErrorsPackage  = "errors"
	defaultFMT            = "fmt"
	defaultReflect        = "reflect"
	defaultContext        = "context"
	defaultSync           = "sync"
	defaultMetricAlias    = "metric"
	defaultRuntimeAlias   = "pgmesh"
	defaultPGXAlias       = "pgx"
	defaultSlogAlias      = "slog"
	defaultTraceAlias     = "trace"
	defaultSlog           = "log/slog"
	defaultMetric         = "go.opentelemetry.io/otel/metric"
	defaultTrace          = "go.opentelemetry.io/otel/trace"
	defaultReadInterface  = "readQuerier"
	defaultWriteInterface = "writeQuerier"
	defaultStoreInterface = "Store"
	defaultStoreType      = "queryStore"
	defaultReadType       = "readQueries"
	defaultWriteType      = "writeQueries"
	defaultReadNew        = "newReadQueries"
	defaultWriteNew       = "newWriteQueries"
	defaultStoreNew       = "NewStore"
	defaultTargetType     = "Queries"
	defaultTargetNew      = "New"
	defaultArgumentName   = "arg"
	defaultReceiverName   = "q"
	defaultPGXPackage     = "github.com/jackc/pgx/v5"
	defaultRuntimePackage = "github.com/sundayfun/pgmesh"
	defaultNodeNew        = "newStoreNode"
	defaultResolver       = "ShardResolver"
	defaultMeshStoreType  = "meshStore"
	defaultGroupType      = "groupedMeshStore"
	defaultShardedNew     = "Sharded"
	generatedHeader       = "// Code generated by pgmesh. DO NOT EDIT."
	mirrorReceiverName    = "mirror"
	mirrorErrorName       = "mirrorErr"
	resultErrorName       = "error"
	cmdMany               = ":many"
	cmdExec               = ":exec"
	cmdExecRows           = ":execrows"
	cmdCopyFrom           = ":copyfrom"
	emptyInterfaceType    = "interface{}"
)

// Generate implements sqlc's CodegenService.Generate hook.
func Generate(_ context.Context, req *plugin.GenerateRequest) (*plugin.GenerateResponse, error) {
	opts, err := parseOptions(req)
	if err != nil {
		return nil, fmt.Errorf("parse options: %w", err)
	}

	queries, imports, err := querySpecs(req, opts)
	if err != nil {
		return nil, fmt.Errorf("build query specifications: %w", err)
	}

	files, err := generateWrapper(opts, queries, imports, req.GetCatalog())
	if err != nil {
		return nil, fmt.Errorf("generate wrappers: %w", err)
	}
	return &plugin.GenerateResponse{Files: files}, nil
}
