// Code generated by pgmesh. DO NOT EDIT.

package one

import (
	"context"
	pgmesh "github.com/sundayfun/pgmesh"
)

// UpsertSettingT is the store parameter type for UpsertSetting.
type UpsertSettingT = UpsertSettingParams

// SettingsReader exposes read queries in the Settings store group.
type SettingsReader interface {
	// GetSetting executes the generated GetSetting query.
	GetSetting(ctx context.Context, key string, storeOptions ...QueryOption) (*ApplicationSetting, error)
}

// SettingsWriter exposes write queries in the Settings store group.
type SettingsWriter interface {
	// UpsertSetting executes the generated UpsertSetting query.
	UpsertSetting(ctx context.Context, arg *UpsertSettingT, storeOptions ...QueryOption) (*ApplicationSetting, error)
}

// Settings exposes all queries in its generated store group.
type Settings interface {
	SettingsReader
	SettingsWriter
}

type telemetrySettingsStore[SK any] struct {
	store  *meshStore[SK]
	target Settings
}

func (q *telemetrySettingsStore[SK]) GetSetting(ctx context.Context, key string, storeOptions ...QueryOption) (result *ApplicationSetting, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Settings", "GetSetting", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetSetting(ctx, key, storeOptions...)
}

func (q *telemetrySettingsStore[SK]) UpsertSetting(ctx context.Context, arg *UpsertSettingT, storeOptions ...QueryOption) (result *ApplicationSetting, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Settings", "UpsertSetting", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.UpsertSetting(ctx, arg, storeOptions...)
}

// WithSettingsFactory configures an optional wrapper for the Settings query group.
// A nil factory leaves the generated query group unwrapped.
func WithSettingsFactory(createSettings func(Settings) Settings) StoreOption {
	return func(options *storeOptions) { options.factories.Settings = createSettings }
}

var _ Settings = (*groupedMeshStore[uint8])(nil)
var _ Settings = (*telemetrySettingsStore[uint8])(nil)

// Settings returns the Settings query group.
func (q *meshStore[SK]) Settings() Settings {
	return q.groups.Settings
}

// GetSetting executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetSetting(ctx context.Context, key string, storeOptions ...QueryOption) (result *ApplicationSetting, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Settings", "GetSetting", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetSetting(ctx, key)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetSetting(ctx, key)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetSetting(ctx, key)
	}
}

// UpsertSetting executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpsertSetting(ctx context.Context, arg *UpsertSettingT, storeOptions ...QueryOption) (result *ApplicationSetting, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Settings", "UpsertSetting", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.UpsertSetting(ctx, arg)
}
