// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	db "github.com/sundayfun/pgmesh/tests/command_shapes/internal"
)

// writeQueries exposes primary-capable generated queries.
type writeQueries struct {
	main    *db.Queries
	mirrors []*db.Queries
}

func newWriteQueries(q *db.Queries, mirrors ...*db.Queries) *writeQueries {
	return &writeQueries{main: q, mirrors: mirrors}
}

// WithTx returns a write wrapper that executes queries through tx.
func (q *writeQueries) WithTx(tx pgx.Tx) *writeQueries {
	return newWriteQueries(q.main.WithTx(tx))
}

// WithMirrors returns a copy that also writes to the supplied mirrors.
func (q *writeQueries) WithMirrors(qs ...*writeQueries) *writeQueries {
	var mirrors []*db.Queries
	mirrors = append(mirrors, q.mirrors...)
	for _, mirror := range qs {
		if mirror == nil {
			continue
		}
		mirrors = append(mirrors, mirror.main)
		mirrors = append(mirrors, mirror.mirrors...)
	}
	return newWriteQueries(q.main, mirrors...)
}

func (q *writeQueries) mirror(fn func(*db.Queries) error) error {
	for _, mirror := range q.mirrors {
		if err := fn(mirror); err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				continue
			}
			return err
		}
	}
	return nil
}

// BatchInsertCommandUsers executes the generated BatchInsertCommandUsers query.
func (q *writeQueries) BatchInsertCommandUsers(ctx context.Context, arg []*db.BatchInsertCommandUsersParams) *db.BatchInsertCommandUsersBatchResults {
	return q.main.BatchInsertCommandUsers(ctx, arg)
}

// CopyCommandUsers executes the generated CopyCommandUsers query.
func (q *writeQueries) CopyCommandUsers(ctx context.Context, arg []*db.CopyCommandUsersParams) (int64, error) {
	rv0, err := q.main.CopyCommandUsers(ctx, arg)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.CopyCommandUsers(ctx, arg)
		return err
	})
	return rv0, mirrorErr
}

// DeleteCommandUser executes the generated DeleteCommandUser query.
func (q *writeQueries) DeleteCommandUser(ctx context.Context, id int64) error {
	if err := q.main.DeleteCommandUser(ctx, id); err != nil {
		return err
	}
	return q.mirror(func(mirror *db.Queries) error {
		return mirror.DeleteCommandUser(ctx, id)
	})
}

// DeleteCommandUsersByTenant executes the generated DeleteCommandUsersByTenant query.
func (q *writeQueries) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64) (int64, error) {
	rv0, err := q.main.DeleteCommandUsersByTenant(ctx, tenantID)
	if err != nil {
		var zero0 int64
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.DeleteCommandUsersByTenant(ctx, tenantID)
		return err
	})
	return rv0, mirrorErr
}

// TouchCommandUser executes the generated TouchCommandUser query.
func (q *writeQueries) TouchCommandUser(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	rv0, err := q.main.TouchCommandUser(ctx, id)
	if err != nil {
		var zero0 pgconn.CommandTag
		return zero0, err
	}
	mirrorErr := q.mirror(func(mirror *db.Queries) error {
		_, err := mirror.TouchCommandUser(ctx, id)
		return err
	})
	return rv0, mirrorErr
}
