// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"github.com/jackc/pgx/v5/pgconn"
	db "github.com/sundayfun/pgmesh/tests/command_shapes/internal"
)

// readQuerier exposes generated read queries.
type readQuerier interface {
	// BatchGetCommandUser executes the generated BatchGetCommandUser query.
	BatchGetCommandUser(ctx context.Context, id []int64) *db.BatchGetCommandUserBatchResults
	// BatchListCommandUsersByTenant executes the generated BatchListCommandUsersByTenant query.
	BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64) *db.BatchListCommandUsersByTenantBatchResults
	// GetCommandUser executes the generated GetCommandUser query.
	GetCommandUser(ctx context.Context, id int64) (*db.User, error)
	// ListCommandUsers executes the generated ListCommandUsers query.
	ListCommandUsers(ctx context.Context) ([]*db.User, error)
}

// writeQuerier exposes generated write queries.
type writeQuerier interface {
	// BatchInsertCommandUsers executes the generated BatchInsertCommandUsers query.
	BatchInsertCommandUsers(ctx context.Context, arg []*db.BatchInsertCommandUsersParams) *db.BatchInsertCommandUsersBatchResults
	// CopyCommandUsers executes the generated CopyCommandUsers query.
	CopyCommandUsers(ctx context.Context, arg []*db.CopyCommandUsersParams) (int64, error)
	// DeleteCommandUser executes the generated DeleteCommandUser query.
	DeleteCommandUser(ctx context.Context, id int64) error
	// DeleteCommandUsersByTenant executes the generated DeleteCommandUsersByTenant query.
	DeleteCommandUsersByTenant(ctx context.Context, tenantID int64) (int64, error)
	// TouchCommandUser executes the generated TouchCommandUser query.
	TouchCommandUser(ctx context.Context, id int64) (pgconn.CommandTag, error)
}

// Store is the topology-independent generated query API.
type Store interface {
	// Commands returns the Commands query group.
	Commands() Commands
}

var _ readQuerier = (*readQueries)(nil)
var _ writeQuerier = (*writeQueries)(nil)
var _ db.Querier = (*queryStore)(nil)
