// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5/pgconn"
	pgmesh "github.com/sundayfun/pgmesh"
	db "github.com/sundayfun/pgmesh/tests/command_shapes/internal"
	"sync"
)

// BatchInsertCommandUsersT is the store parameter type for BatchInsertCommandUsers.
type BatchInsertCommandUsersT = db.BatchInsertCommandUsersParams

// CopyCommandUsersT is the store parameter type for CopyCommandUsers.
type CopyCommandUsersT = db.CopyCommandUsersParams

type copyCommandUsersBatchState struct {
	mu       sync.Mutex
	enabled  bool
	batchers map[string]*pgmesh.CopyBatcher[*db.CopyCommandUsersParams]
}

// WithCopyCommandUsersBatching enables asynchronous micro-batching for CopyCommandUsers.
func WithCopyCommandUsersBatching(config pgmesh.CopyBatchConfig) StoreOption {
	configured := config
	return func(options *storeOptions) { options.copyBatching.copyCommandUsers = &configured }
}

// CommandsReader exposes read queries in the Commands store group.
type CommandsReader interface {
	// BatchGetCommandUser executes the generated BatchGetCommandUser query.
	BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults
	// BatchListCommandUsersByTenant executes the generated BatchListCommandUsersByTenant query.
	BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults
	// GetCommandUser executes the generated GetCommandUser query.
	GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (*db.User, error)
	// ListCommandUsers executes the generated ListCommandUsers query.
	ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) ([]*db.User, error)
}

// CommandsWriter exposes write queries in the Commands store group.
type CommandsWriter interface {
	// BatchInsertCommandUsers executes the generated BatchInsertCommandUsers query.
	BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults
	// CopyCommandUsers executes the generated CopyCommandUsers query.
	CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (int64, error)
	// CopyCommandUsersAsync accepts rows for asynchronous COPY.
	CopyCommandUsersAsync(ctx context.Context, arg []*CopyCommandUsersT) *pgmesh.Future[int64]
	// FlushCopyCommandUsers drains asynchronous submissions accepted before its barrier.
	FlushCopyCommandUsers(ctx context.Context) error
	// DeleteCommandUser executes the generated DeleteCommandUser query.
	DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) error
	// DeleteCommandUsersByTenant executes the generated DeleteCommandUsersByTenant query.
	DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (int64, error)
	// TouchCommandUser executes the generated TouchCommandUser query.
	TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (pgconn.CommandTag, error)
}

// Commands exposes all queries in its generated store group.
type Commands interface {
	CommandsReader
	CommandsWriter
}

type telemetryCommandsStore[SK any] struct {
	store  *meshStore[SK]
	target Commands
}

func (q *telemetryCommandsStore[SK]) BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults {
	return q.target.BatchGetCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults {
	return q.target.BatchInsertCommandUsers(ctx, arg, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults {
	return q.target.BatchListCommandUsersByTenant(ctx, tenantID, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "CopyCommandUsers", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.CopyCommandUsers(ctx, arg, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) CopyCommandUsersAsync(ctx context.Context, arg []*CopyCommandUsersT) *pgmesh.Future[int64] {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "CopyCommandUsersAsync", pgmesh.QueryKindWrite)
	future := q.target.CopyCommandUsersAsync(ctx, arg)
	return pgmesh.RunFuture(func() (int64, error) {
		count, err := future.Await(context.Background())
		storeSpan.End(err)
		return count, err
	})
}

func (q *telemetryCommandsStore[SK]) FlushCopyCommandUsers(ctx context.Context) error {
	return q.target.FlushCopyCommandUsers(ctx)
}

func (q *telemetryCommandsStore[SK]) DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "DeleteCommandUser", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "DeleteCommandUsersByTenant", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.DeleteCommandUsersByTenant(ctx, tenantID, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result *db.User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "GetCommandUser", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetCommandUser(ctx, id, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) (result []*db.User, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "ListCommandUsers", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.ListCommandUsers(ctx, storeOptions...)
}

func (q *telemetryCommandsStore[SK]) TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result pgconn.CommandTag, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreQuerySpan(ctx, "Commands", "TouchCommandUser", pgmesh.QueryKindWrite)
	defer func() { storeSpan.End(err) }()
	return q.target.TouchCommandUser(ctx, id, storeOptions...)
}

// WithCommandsFactory configures an optional wrapper for the Commands query group.
// A nil factory leaves the generated query group unwrapped.
func WithCommandsFactory(createCommands func(Commands) Commands) StoreOption {
	return func(options *storeOptions) { options.factories.Commands = createCommands }
}

var _ Commands = (*groupedMeshStore[uint8])(nil)
var _ Commands = (*telemetryCommandsStore[uint8])(nil)

// Commands returns the Commands query group.
func (q *meshStore[SK]) Commands() Commands {
	return q.groups.Commands
}

// BatchGetCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchGetCommandUser(ctx context.Context, id []int64, storeOptions ...QueryOption) *db.BatchGetCommandUserBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Resolve(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		return target.BatchGetCommandUser(ctx, id)

	// Explicit primary reads bypass replicas.
	case options.primary:
		route := shard.WriteRoute()
		return route.Target.BatchGetCommandUser(ctx, id)

	// Ordinary reads use the shard's replica route.
	default:
		route := shard.ReadRoute()
		return route.Target.BatchGetCommandUser(ctx, id)
	}
}

// BatchInsertCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersT, storeOptions ...QueryOption) *db.BatchInsertCommandUsersBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Resolve(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	if options.tx != nil {
		target = target.WithTx(options.tx)
	}

	// Execute the write on the selected target.
	return target.BatchInsertCommandUsers(ctx, arg)
}

// BatchListCommandUsersByTenant executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64, storeOptions ...QueryOption) *db.BatchListCommandUsersByTenantBatchResults {
	// Resolve the shard key for this topology.
	var shardKey SK
	shard, _ := q.store.mesh.Resolve(shardKey)

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		return target.BatchListCommandUsersByTenant(ctx, tenantID)

	// Explicit primary reads bypass replicas.
	case options.primary:
		route := shard.WriteRoute()
		return route.Target.BatchListCommandUsersByTenant(ctx, tenantID)

	// Ordinary reads use the shard's replica route.
	default:
		route := shard.ReadRoute()
		return route.Target.BatchListCommandUsersByTenant(ctx, tenantID)
	}
}

// CopyCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersT, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "CopyCommandUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode, 1)
	ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.CopyCommandUsers(ctx, arg)
}

// CopyCommandUsersAsync accepts rows for asynchronous COPY.
func (q *groupedMeshStore[SK]) CopyCommandUsersAsync(ctx context.Context, arg []*CopyCommandUsersT) *pgmesh.Future[int64] {
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "CopyCommandUsersAsync", pgmesh.QueryKindWrite)
	finish := func(future *pgmesh.Future[int64]) *pgmesh.Future[int64] {
		return pgmesh.RunFuture(func() (int64, error) {
			count, err := future.Await(context.Background())
			querySpan.End(err)
			return count, err
		})
	}

	type asyncCopyShardGroup struct {
		shard   pgmesh.ResolvedShard[*readQueries, *queryStore]
		args    []*db.CopyCommandUsersParams
		batcher *pgmesh.CopyBatcher[*db.CopyCommandUsersParams]
	}
	var shardKey SK
	shard, routeErr := q.store.mesh.Resolve(shardKey)
	if routeErr != nil {
		return finish(pgmesh.ResolvedFuture[int64](0, routeErr))
	}
	groups := []*asyncCopyShardGroup{{shard: shard, args: arg}}
	querySpan.SetRoute(pgmesh.RouteModePrimary, 1)
	if len(groups) == 0 {
		return finish(pgmesh.ResolvedFuture[int64](0, nil))
	}
	state := q.store.copyCommandUsersBatch
	state.mu.Lock()
	if err := ctx.Err(); err != nil {
		state.mu.Unlock()
		return finish(pgmesh.ResolvedFuture[int64](0, err))
	}
	for _, shardGroup := range groups {
		shardGroup.batcher = state.batchers[shardGroup.shard.ReplicaSetName()]
		if shardGroup.batcher == nil {
			state.mu.Unlock()
			err := fmt.Errorf("query CopyCommandUsersAsync has no copy batcher for replica set %q", shardGroup.shard.ReplicaSetName())
			return finish(pgmesh.ResolvedFuture[int64](0, err))
		}
	}
	acceptedContext := context.WithoutCancel(ctx)
	type asyncCopyResult struct {
		shardName string
		future    *pgmesh.Future[int64]
	}
	asyncResults := make([]asyncCopyResult, 0, len(groups))
	for _, shardGroup := range groups {
		var future *pgmesh.Future[int64]
		if state.enabled {
			future = shardGroup.batcher.Submit(acceptedContext, shardGroup.args)
		} else {
			future = shardGroup.batcher.SubmitUnbatched(acceptedContext, shardGroup.args)
		}
		asyncResults = append(asyncResults, asyncCopyResult{shardName: shardGroup.shard.ReplicaSetName(), future: future})
	}
	state.mu.Unlock()

	combined := pgmesh.RunFuture(func() (int64, error) {
		var count int64
		copyErrors := make([]error, 0, len(asyncResults))
		for _, asyncResult := range asyncResults {
			shardCount, err := asyncResult.future.Await(context.Background())
			if err != nil {
				copyErrors = append(copyErrors, fmt.Errorf("query CopyCommandUsers on replica set %q: %w", asyncResult.shardName, err))
				continue
			}
			count += shardCount
		}
		if err := errors.Join(copyErrors...); err != nil {
			return 0, err
		}
		return count, nil
	})
	return finish(combined)
}

// FlushCopyCommandUsers drains asynchronous submissions accepted before its barrier.
func (q *groupedMeshStore[SK]) FlushCopyCommandUsers(ctx context.Context) error {
	state := q.store.copyCommandUsersBatch
	state.mu.Lock()
	type copyFlushResult struct {
		shardName string
		future    *pgmesh.Future[struct{}]
	}
	flushes := make([]copyFlushResult, 0, len(q.store.mesh.ReplicaSets()))
	for _, replicaSet := range q.store.mesh.ReplicaSets() {
		if batcher := state.batchers[replicaSet.Name()]; batcher != nil {
			flushes = append(flushes, copyFlushResult{shardName: replicaSet.Name(), future: batcher.FlushAsync()})
		}
	}
	state.mu.Unlock()
	flushErrors := make([]error, 0, len(flushes))
	for _, flushResult := range flushes {
		if _, err := flushResult.future.Await(ctx); err != nil {
			flushErrors = append(flushErrors, fmt.Errorf("flush CopyCommandUsers on replica set %q: %w", flushResult.shardName, err))
			if ctx.Err() != nil {
				break
			}
		}
	}
	return errors.Join(flushErrors...)
}

// DeleteCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) DeleteCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "DeleteCommandUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode, 1)
	ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.DeleteCommandUser(ctx, id)
}

// DeleteCommandUsersByTenant executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64, storeOptions ...QueryOption) (result int64, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "DeleteCommandUsersByTenant", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode, 1)
	ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.DeleteCommandUsersByTenant(ctx, tenantID)
}

// GetCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result *db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "GetCommandUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(pgmesh.RouteModeTransaction, 1)
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeTransaction)
		defer func() { physicalQuerySpan.End(err) }()
		return target.GetCommandUser(ctx, id)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(pgmesh.RouteModePrimary, 1)
		route := shard.WriteRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModePrimary)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.GetCommandUser(ctx, id)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(pgmesh.RouteModeRead, 1)
		route := shard.ReadRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeRead)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.GetCommandUser(ctx, id)
	}
}

// ListCommandUsers executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) ListCommandUsers(ctx context.Context, storeOptions ...QueryOption) (result []*db.User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "ListCommandUsers", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(pgmesh.RouteModeTransaction, 1)
		route := shard.WriteRoute()
		target := route.Target.WithTx(options.tx)
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeTransaction)
		defer func() { physicalQuerySpan.End(err) }()
		return target.ListCommandUsers(ctx)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(pgmesh.RouteModePrimary, 1)
		route := shard.WriteRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModePrimary)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.ListCommandUsers(ctx)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(pgmesh.RouteModeRead, 1)
		route := shard.ReadRoute()
		ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), pgmesh.RouteModeRead)
		defer func() { physicalQuerySpan.End(err) }()
		return route.Target.ListCommandUsers(ctx)
	}
}

// TouchCommandUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) TouchCommandUser(ctx context.Context, id int64, storeOptions ...QueryOption) (result pgconn.CommandTag, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartLogicalQuerySpan(ctx, "Commands", "TouchCommandUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	shard, err := q.store.mesh.Resolve(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	route := shard.WriteRoute()
	target := route.Target
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(mode, 1)
	ctx, physicalQuerySpan := querySpan.StartPhysicalQuerySpan(ctx, route.Metadata(), mode)
	defer func() { physicalQuerySpan.End(err) }()
	return target.TouchCommandUser(ctx, id)
}
