// Code generated by pgmesh. DO NOT EDIT.

package store

import (
	"context"
	"github.com/jackc/pgx/v5"
	db "github.com/sundayfun/pgmesh/tests/command_shapes/internal"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *db.Queries
}

func newReadQueries(q *db.Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// BatchGetCommandUser executes the generated BatchGetCommandUser query.
func (q *readQueries) BatchGetCommandUser(ctx context.Context, id []int64) *db.BatchGetCommandUserBatchResults {
	return q.main.BatchGetCommandUser(ctx, id)
}

// BatchListCommandUsersByTenant executes the generated BatchListCommandUsersByTenant query.
func (q *readQueries) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64) *db.BatchListCommandUsersByTenantBatchResults {
	return q.main.BatchListCommandUsersByTenant(ctx, tenantID)
}

// GetCommandUser executes the generated GetCommandUser query.
func (q *readQueries) GetCommandUser(ctx context.Context, id int64) (*db.User, error) {
	rv0, err := q.main.GetCommandUser(ctx, id)
	if err != nil {
		var zero0 *db.User
		return zero0, err
	}
	return rv0, nil
}

// ListCommandUsers executes the generated ListCommandUsers query.
func (q *readQueries) ListCommandUsers(ctx context.Context) ([]*db.User, error) {
	rv0, err := q.main.ListCommandUsers(ctx)
	if err != nil {
		var zero0 []*db.User
		return zero0, err
	}
	return rv0, nil
}
