// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package internal

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchGetCommandUser = `-- name: BatchGetCommandUser :batchone
SELECT id, tenant_id, name
FROM users
WHERE id = $1
`

type BatchGetCommandUserBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

// kind: read
// store: Commands
func (q *Queries) BatchGetCommandUser(ctx context.Context, id []int64) *BatchGetCommandUserBatchResults {
	batch := &pgx.Batch{}
	for _, a := range id {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchGetCommandUser, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchGetCommandUserBatchResults{br, len(id), false}
}

func (b *BatchGetCommandUserBatchResults) QueryRow(f func(int, *User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, nil, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&i.ID, &i.TenantID, &i.Name)
		if f != nil {
			f(t, &i, err)
		}
	}
}

func (b *BatchGetCommandUserBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchInsertCommandUsers = `-- name: BatchInsertCommandUsers :batchexec
INSERT INTO users (id, tenant_id, name)
VALUES ($1, $2, $3)
`

type BatchInsertCommandUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchInsertCommandUsersParams struct {
	ID       int64
	TenantID int64
	Name     string
}

// kind: write
// store: Commands
func (q *Queries) BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersParams) *BatchInsertCommandUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ID,
			a.TenantID,
			a.Name,
		}
		batch.Queue(batchInsertCommandUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchInsertCommandUsersBatchResults{br, len(arg), false}
}

func (b *BatchInsertCommandUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchInsertCommandUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const batchListCommandUsersByTenant = `-- name: BatchListCommandUsersByTenant :batchmany
SELECT id, tenant_id, name
FROM users
WHERE tenant_id = $1
ORDER BY id
`

type BatchListCommandUsersByTenantBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

// kind: read
// store: Commands
func (q *Queries) BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64) *BatchListCommandUsersByTenantBatchResults {
	batch := &pgx.Batch{}
	for _, a := range tenantID {
		vals := []interface{}{
			a,
		}
		batch.Queue(batchListCommandUsersByTenant, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchListCommandUsersByTenantBatchResults{br, len(tenantID), false}
}

func (b *BatchListCommandUsersByTenantBatchResults) Query(f func(int, []*User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var items []*User
		if b.closed {
			if f != nil {
				f(t, items, ErrBatchAlreadyClosed)
			}
			continue
		}
		err := func() error {
			rows, err := b.br.Query()
			if err != nil {
				return err
			}
			defer rows.Close()
			for rows.Next() {
				var i User
				if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
					return err
				}
				items = append(items, &i)
			}
			return rows.Err()
		}()
		if f != nil {
			f(t, items, err)
		}
	}
}

func (b *BatchListCommandUsersByTenantBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
