// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package internal

import (
	"context"
)

// iteratorForCopyCommandUsers implements pgx.CopyFromSource.
type iteratorForCopyCommandUsers struct {
	rows                 []*CopyCommandUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyCommandUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyCommandUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TenantID,
		r.rows[0].Name,
	}, nil
}

func (r iteratorForCopyCommandUsers) Err() error {
	return nil
}

// kind: write
// store: Commands
func (q *Queries) CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "tenant_id", "name"}, &iteratorForCopyCommandUsers{rows: arg})
}
