// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	// kind: read
	// store: Commands
	BatchGetCommandUser(ctx context.Context, id []int64) *BatchGetCommandUserBatchResults
	// kind: write
	// store: Commands
	BatchInsertCommandUsers(ctx context.Context, arg []*BatchInsertCommandUsersParams) *BatchInsertCommandUsersBatchResults
	// kind: read
	// store: Commands
	BatchListCommandUsersByTenant(ctx context.Context, tenantID []int64) *BatchListCommandUsersByTenantBatchResults
	// kind: write
	// store: Commands
	CopyCommandUsers(ctx context.Context, arg []*CopyCommandUsersParams) (int64, error)
	// kind: write
	// store: Commands
	DeleteCommandUser(ctx context.Context, id int64) error
	// kind: write
	// store: Commands
	DeleteCommandUsersByTenant(ctx context.Context, tenantID int64) (int64, error)
	// kind: read
	// store: Commands
	GetCommandUser(ctx context.Context, id int64) (*User, error)
	// kind: read
	// store: Commands
	ListCommandUsers(ctx context.Context) ([]*User, error)
	// kind: write
	// store: Commands
	TouchCommandUser(ctx context.Context, id int64) (pgconn.CommandTag, error)
}

var _ Querier = (*Queries)(nil)
