// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package internal

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type CopyCommandUsersParams struct {
	ID       int64
	TenantID int64
	Name     string
}

const deleteCommandUser = `-- name: DeleteCommandUser :exec
DELETE FROM users
WHERE id = $1
`

// kind: write
// store: Commands
func (q *Queries) DeleteCommandUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCommandUser, id)
	return err
}

const deleteCommandUsersByTenant = `-- name: DeleteCommandUsersByTenant :execrows
DELETE FROM users
WHERE tenant_id = $1
`

// kind: write
// store: Commands
func (q *Queries) DeleteCommandUsersByTenant(ctx context.Context, tenantID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommandUsersByTenant, tenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommandUser = `-- name: GetCommandUser :one
SELECT id, tenant_id, name
FROM users
WHERE id = $1
`

// kind: read
// store: Commands
func (q *Queries) GetCommandUser(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, getCommandUser, id)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}

const listCommandUsers = `-- name: ListCommandUsers :many
SELECT id, tenant_id, name
FROM users
ORDER BY id
`

// kind: read
// store: Commands
func (q *Queries) ListCommandUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listCommandUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCommandUser = `-- name: TouchCommandUser :execresult
UPDATE users
SET name = name
WHERE id = $1
`

// kind: write
// store: Commands
func (q *Queries) TouchCommandUser(ctx context.Context, id int64) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, touchCommandUser, id)
}
