// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package internal

import (
	"context"
)

// iteratorForCopyUsers implements pgx.CopyFromSource.
type iteratorForCopyUsers struct {
	rows                 []*CopyUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TenantID,
		r.rows[0].Name,
	}, nil
}

func (r iteratorForCopyUsers) Err() error {
	return nil
}

// kind: write
// shard: tenantKey(tenant_id)
// store: Users
func (q *Queries) CopyUsers(ctx context.Context, arg []*CopyUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "tenant_id", "name"}, &iteratorForCopyUsers{rows: arg})
}
