// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package samepackage

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CopyUsersParams struct {
	ID       int64
	TenantID int64
	Name     string
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name
`

type CreateUserParams struct {
	ID       int64
	TenantID int64
	Name     string
}

// kind: write
// shard: tenant(tenant_id)
// store: Users
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.TenantID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

// kind: write
// shard: all()
// store: Users
func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllUsers)
	return err
}

const deleteAllUsersByName = `-- name: DeleteAllUsersByName :execrows
DELETE FROM users
WHERE name = $1
`

// kind: write
// shard: all()
// store: Users
func (q *Queries) DeleteAllUsersByName(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllUsersByName, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, tenant_id, summary, state, source, active_window
FROM analyses
WHERE tenant_id = $1 AND id = $2
`

type GetAnalysisParams struct {
	TenantID int64
	ID       int64
}

// kind: read
// shard: tenant(tenant_id)
// store: Analyses
func (q *Queries) GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, arg.TenantID, arg.ID)
	var i Analysis
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Description,
		&i.State,
		&i.Source,
		&i.ActiveWindow,
	)
	return &i, err
}

const getTenantUserAnalysis = `-- name: GetTenantUserAnalysis :one
SELECT users.id AS user_id, analyses.id AS analysis_id
FROM users
JOIN analyses ON analyses.tenant_id = users.tenant_id
WHERE users.id = $1
  AND analyses.id = $2
`

type GetTenantUserAnalysisParams struct {
	UserID     int64
	AnalysisID int64
}

type GetTenantUserAnalysisRow struct {
	UserID     int64
	AnalysisID int64
}

// kind: read
// shard: tenant(tenant_id)
// store: Analyses
func (q *Queries) GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisParams) (*GetTenantUserAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getTenantUserAnalysis, arg.UserID, arg.AnalysisID)
	var i GetTenantUserAnalysisRow
	err := row.Scan(&i.UserID, &i.AnalysisID)
	return &i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, name
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetUserParams struct {
	TenantID int64
	ID       int64
}

// kind: read
// shard: tenant(tenant_id)
// store: Users
func (q *Queries) GetUser(ctx context.Context, arg *GetUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT id, tenant_id, name
FROM users
ORDER BY id
`

// kind: read
// shard: all()
// store: Users
func (q *Queries) ListAllUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listP2PMessageIDsByChat = `-- name: ListP2PMessageIDsByChat :many
SELECT id FROM "message"
WHERE in_group = FALSE
  AND LEAST(user_id, to_user_or_group_id) = LEAST($2::bigint, $3::bigint)
  AND GREATEST(user_id, to_user_or_group_id) = GREATEST($2::bigint, $3::bigint)
  AND created_at >= $4::timestamptz
  AND deleted_at IS NULL
  AND ($5::public.xid IS NULL OR id < $5::public.xid)
ORDER BY id DESC
LIMIT $1
`

type ListP2PMessageIDsByChatParams struct {
	Limit        int32
	UserID       int64
	PeerID       int64
	CreatedSince pgtype.Timestamptz
	LastID       interface{}
}

// kind: read
// shard: messageKey(user_id, to_user_or_group_id, in_group)
// store: QueryMessage
func (q *Queries) ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listP2PMessageIDsByChat,
		arg.Limit,
		arg.UserID,
		arg.PeerID,
		arg.CreatedSince,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var id interface{}
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listP2PMessagesByChat = `-- name: ListP2PMessagesByChat :many
SELECT id, user_id, to_user_or_group_id, in_group, created_at, deleted_at FROM "message"
WHERE in_group = FALSE
  AND LEAST(user_id, to_user_or_group_id) = LEAST($2::bigint, $3::bigint)
  AND GREATEST(user_id, to_user_or_group_id) = GREATEST($2::bigint, $3::bigint)
  AND created_at >= $4::timestamptz
  AND deleted_at IS NULL
  AND ($5::public.xid IS NULL OR id < $5::public.xid)
ORDER BY id DESC
LIMIT $1
`

type ListP2PMessagesByChatParams struct {
	Limit        int32
	UserID       int64
	PeerID       int64
	CreatedSince pgtype.Timestamptz
	LastID       interface{}
}

// kind: read
// shard: messageKey(user_id, to_user_or_group_id, in_group)
// store: QueryMessage
func (q *Queries) ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatParams) ([]*Message, error) {
	rows, err := q.db.Query(ctx, listP2PMessagesByChat,
		arg.Limit,
		arg.UserID,
		arg.PeerID,
		arg.CreatedSince,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ToUserOrGroupID,
			&i.InGroup,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, tenant_id, name
FROM users
WHERE id = ANY($1::bigint[])
`

// kind: read
// shard: tenant(tenant_id)
// store: Users
func (q *Queries) ListUsersByIDs(ctx context.Context, ids []int64) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $3
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, name
`

type UpdateUserNameParams struct {
	TenantID int64
	ID       int64
	Name     string
}

// kind: write
// shard: tenant(tenant_id)
// store: Users
func (q *Queries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.TenantID, arg.ID, arg.Name)
	var i User
	err := row.Scan(&i.ID, &i.TenantID, &i.Name)
	return &i, err
}
