// Code generated by pgmesh. DO NOT EDIT.

package samepackage

import (
	"context"
	"errors"
	"fmt"
	pgmesh "github.com/sundayfun/pgmesh"
	"reflect"
	"sync"
)

// ListUsersByIDShardParams combines sqlc and routing-only shard parameters for ListUsersByID.
type ListUsersByIDShardParams struct {
	ID       int64
	TenantID int64
}

// UsersReader exposes read queries in the Users store group.
type UsersReader interface {
	// GetUser executes the generated GetUser query.
	GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (*User, error)
	// ListAllUsers executes the generated ListAllUsers query.
	ListAllUsers(ctx context.Context, storeOptions ...QueryOption) ([]*User, error)
	// ListUsersByID executes the generated ListUsersByID query.
	ListUsersByID(ctx context.Context, arg []*ListUsersByIDShardParams, storeOptions ...QueryOption) ([]*User, error)
}

// UsersWriter exposes write queries in the Users store group.
type UsersWriter interface {
	// CopyUsers executes the generated CopyUsers query.
	CopyUsers(ctx context.Context, arg []*CopyUsersParams, storeOptions ...QueryOption) (int64, error)
	// CreateUser executes the generated CreateUser query.
	CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (*User, error)
	// DeleteAllUsers executes the generated DeleteAllUsers query.
	DeleteAllUsers(ctx context.Context, storeOptions ...QueryOption) error
	// DeleteAllUsersByName executes the generated DeleteAllUsersByName query.
	DeleteAllUsersByName(ctx context.Context, name string, storeOptions ...QueryOption) (int64, error)
	// UpdateUserName executes the generated UpdateUserName query.
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (*User, error)
}

// Users exposes all queries in its generated store group.
type Users interface {
	UsersReader
	UsersWriter
}

var _ Users = (*groupedMeshStore[uint8])(nil)

// Users returns the Users query group.
func (q *meshStore[SK]) Users() Users {
	return &groupedMeshStore[SK]{store: q}
}

// CopyUsers groups rows by physical shard and executes one copy per group.
func (q *groupedMeshStore[SK]) CopyUsers(ctx context.Context, arg []*CopyUsersParams, storeOptions ...QueryOption) (result int64, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "CopyUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	type copyShardGroup struct {
		shard *pgmesh.Shard[*readQueries, *queryStore]
		args  []*CopyUsersParams
	}
	groupsByName := make(map[string]*copyShardGroup)
	for inputIndex, item := range arg {
		var shardKey SK
		if q.store.resolver != nil {
			shardKey = q.store.resolver.Tenant(item.TenantID)
		}
		shard, routeErr := q.store.mesh.Shard(shardKey)
		if routeErr != nil {
			err = fmt.Errorf("route CopyUsers input %d: %w", inputIndex, routeErr)
			return result, err
		}
		shardGroup := groupsByName[shard.Name()]
		if shardGroup == nil {
			shardGroup = &copyShardGroup{shard: shard, args: make([]*CopyUsersParams, 0)}
			groupsByName[shard.Name()] = shardGroup
		}
		shardGroup.args = append(shardGroup.args, item)
	}

	groups := make([]*copyShardGroup, 0, len(groupsByName))
	for _, shard := range q.store.mesh.AllShards() {
		if shardGroup := groupsByName[shard.Name()]; shardGroup != nil {
			groups = append(groups, shardGroup)
		}
	}
	if options.tx != nil && len(groups) > 1 {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction)
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		mode = pgmesh.RouteModeTransaction
	}
	querySpan.SetMultiRoute(mode)
	if len(groups) == 0 {
		return result, err
	}

	type copyResult struct {
		count int64
		err   error
	}
	copyResults := make([]copyResult, len(groups))
	var waitGroup sync.WaitGroup
	for index, shardGroup := range groups {
		waitGroup.Go(func() {
			target := shardGroup.shard.Write()
			if options.tx != nil {
				target = target.WithTx(options.tx)
			}
			copyResults[index].count, copyResults[index].err = target.CopyUsers(ctx, shardGroup.args)
		})
	}
	waitGroup.Wait()

	copyErrors := make([]error, 0, len(groups))
	for index, copyResult := range copyResults {
		if copyResult.err != nil {
			copyErrors = append(copyErrors, fmt.Errorf("query CopyUsers on replica set %q: %w", groups[index].shard.Name(), copyResult.err))
		}
	}
	err = errors.Join(copyErrors...)
	if err != nil {
		return result, err
	}
	for _, copyResult := range copyResults {
		result += copyResult.count
	}
	return result, err
}

// CreateUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) CreateUser(ctx context.Context, arg *CreateUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "CreateUser", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.CreateUser(ctx, arg)
}

// DeleteAllUsers executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) DeleteAllUsers(ctx context.Context, storeOptions ...QueryOption) (err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "DeleteAllUsers", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction)
		err = pgmesh.ErrCrossShardTransaction
		return err
	}

	mode := pgmesh.RouteModePrimary
	querySpan.SetMultiRoute(mode)

	type shardResult struct {
		err error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			shardResults[index].err = shard.Write().DeleteAllUsers(ctx)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query DeleteAllUsers on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return err
	}
	return err
}

// DeleteAllUsersByName executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) DeleteAllUsersByName(ctx context.Context, name string, storeOptions ...QueryOption) (result int64, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "DeleteAllUsersByName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction)
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModePrimary
	querySpan.SetMultiRoute(mode)

	type shardResult struct {
		value int64
		err   error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			shardResults[index].value, shardResults[index].err = shard.Write().DeleteAllUsersByName(ctx, name)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query DeleteAllUsersByName on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return result, err
	}
	for _, shardResult := range shardResults {
		result += shardResult.value
	}
	return result, err
}

// GetUser executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetUser(ctx context.Context, arg *GetUserParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "GetUser", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetUser(ctx, arg)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetUser(ctx, arg)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetUser(ctx, arg)
	}
}

// ListAllUsers executes the generated query on every physical shard.
func (q *groupedMeshStore[SK]) ListAllUsers(ctx context.Context, storeOptions ...QueryOption) (result []*User, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "ListAllUsers", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	shards := q.store.mesh.AllShards()
	if options.tx != nil {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction)
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModeRead
	if options.primary {
		mode = pgmesh.RouteModePrimary
	}
	querySpan.SetMultiRoute(mode)

	type shardResult struct {
		value []*User
		err   error
	}
	shardResults := make([]shardResult, len(shards))
	var group sync.WaitGroup
	for index, shard := range shards {
		group.Go(func() {
			if options.primary {
				shardResults[index].value, shardResults[index].err = shard.Write().ListAllUsers(ctx)
				return
			}
			shardResults[index].value, shardResults[index].err = shard.Read().ListAllUsers(ctx)
		})
	}
	group.Wait()

	shardErrors := make([]error, 0, len(shards))
	for index, shardResult := range shardResults {
		if shardResult.err != nil {
			shardErrors = append(shardErrors, fmt.Errorf("query ListAllUsers on replica set %q: %w", shards[index].Name(), shardResult.err))
		}
	}
	err = errors.Join(shardErrors...)
	if err != nil {
		return result, err
	}
	for _, shardResult := range shardResults {
		result = append(result, shardResult.value...)
	}
	return result, err
}

// ListUsersByID groups lookup values by physical shard and restores input-key result order.
func (q *groupedMeshStore[SK]) ListUsersByID(ctx context.Context, arg []*ListUsersByIDShardParams, storeOptions ...QueryOption) (result []*User, err error) {
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "ListUsersByID", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	options := applyQueryOptions(storeOptions...)
	type manyShardGroup struct {
		shard     *pgmesh.Shard[*readQueries, *queryStore]
		args      []int64
		requested map[any]struct{}
	}
	type manyOrderItem struct {
		shardName string
		key       any
	}
	groupsByName := make(map[string]*manyShardGroup)
	orderedItems := make([]manyOrderItem, 0)
	for inputIndex, item := range arg {
		if item == nil {
			err = fmt.Errorf("route ListUsersByID input %d: shard parameter is nil", inputIndex)
			return result, err
		}
		lookupValue := item.ID
		lookupKey := any(lookupValue)
		if lookupKey != nil && !reflect.ValueOf(lookupKey).Comparable() {
			err = fmt.Errorf("route ListUsersByID input %d: lookup key type %T is not comparable", inputIndex, lookupKey)
			return result, err
		}
		var shardKey SK
		if q.store.resolver != nil {
			shardKey = q.store.resolver.Tenant(item.TenantID)
		}
		shard, routeErr := q.store.mesh.Shard(shardKey)
		if routeErr != nil {
			err = fmt.Errorf("route ListUsersByID input %d: %w", inputIndex, routeErr)
			return result, err
		}
		shardGroup := groupsByName[shard.Name()]
		if shardGroup == nil {
			shardGroup = &manyShardGroup{shard: shard, args: make([]int64, 0), requested: make(map[any]struct{})}
			groupsByName[shard.Name()] = shardGroup
		}
		if _, exists := shardGroup.requested[lookupKey]; exists {
			continue
		}
		shardGroup.requested[lookupKey] = struct{}{}
		shardGroup.args = append(shardGroup.args, lookupValue)
		orderedItems = append(orderedItems, manyOrderItem{shardName: shard.Name(), key: lookupKey})
	}

	groups := make([]*manyShardGroup, 0, len(groupsByName))
	for _, shard := range q.store.mesh.AllShards() {
		if shardGroup := groupsByName[shard.Name()]; shardGroup != nil {
			groups = append(groups, shardGroup)
		}
	}
	if options.tx != nil && len(groups) > 1 {
		querySpan.SetMultiRoute(pgmesh.RouteModeTransaction)
		err = pgmesh.ErrCrossShardTransaction
		return result, err
	}

	mode := pgmesh.RouteModeRead
	if options.primary {
		mode = pgmesh.RouteModePrimary
	}
	if options.tx != nil {
		mode = pgmesh.RouteModeTransaction
	}
	querySpan.SetMultiRoute(mode)
	if len(groups) == 0 {
		return result, err
	}

	type manyResult struct {
		value []*User
		err   error
	}
	groupResults := make([]manyResult, len(groups))
	var waitGroup sync.WaitGroup
	for index, shardGroup := range groups {
		waitGroup.Go(func() {
			switch {
			case options.tx != nil:
				groupResults[index].value, groupResults[index].err = shardGroup.shard.Write().WithTx(options.tx).ListUsersByID(ctx, shardGroup.args)
			case options.primary:
				groupResults[index].value, groupResults[index].err = shardGroup.shard.Write().ListUsersByID(ctx, shardGroup.args)
			default:
				groupResults[index].value, groupResults[index].err = shardGroup.shard.Read().ListUsersByID(ctx, shardGroup.args)
			}
		})
	}
	waitGroup.Wait()

	groupErrors := make([]error, 0, len(groups))
	for index, groupResult := range groupResults {
		if groupResult.err != nil {
			groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByID on replica set %q: %w", groups[index].shard.Name(), groupResult.err))
		}
	}
	err = errors.Join(groupErrors...)
	if err != nil {
		return result, err
	}

	rowsByGroup := make(map[string]map[any][]*User, len(groups))
	for groupIndex, groupResult := range groupResults {
		rowsByKey := make(map[any][]*User)
		rowsByGroup[groups[groupIndex].shard.Name()] = rowsByKey
		for resultIndex, row := range groupResult.value {
			if row == nil {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByID on replica set %q returned nil row at result %d", groups[groupIndex].shard.Name(), resultIndex))
				continue
			}
			resultKey := any(row.ID)
			if resultKey != nil && !reflect.ValueOf(resultKey).Comparable() {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByID on replica set %q result %d has non-comparable lookup key type %T", groups[groupIndex].shard.Name(), resultIndex, resultKey))
				continue
			}
			if _, requested := groups[groupIndex].requested[resultKey]; !requested {
				groupErrors = append(groupErrors, fmt.Errorf("query ListUsersByID on replica set %q result %d has an unrequested lookup key", groups[groupIndex].shard.Name(), resultIndex))
				continue
			}
			rowsByKey[resultKey] = append(rowsByKey[resultKey], row)
		}
	}
	err = errors.Join(groupErrors...)
	if err != nil {
		return result, err
	}

	for _, orderedItem := range orderedItems {
		result = append(result, rowsByGroup[orderedItem.shardName][orderedItem.key]...)
	}
	return result, err
}

// UpdateUserName executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams, storeOptions ...QueryOption) (result *User, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Users", "UpdateUserName", pgmesh.QueryKindWrite)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	// Select the primary write route, or the transaction when provided.
	target := shard.Write()
	mode := pgmesh.RouteModePrimary
	if options.tx != nil {
		target = target.WithTx(options.tx)
		mode = pgmesh.RouteModeTransaction
	}

	// Execute the write after recording its resolved route.
	querySpan.SetRoute(shard.VShardIndex(), shard.Name(), mode)
	return target.UpdateUserName(ctx, arg)
}
