// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package samepackage

import (
	"context"
)

type Querier interface {
	// kind: write
	// shard: tenant(tenant_id)
	// store: Users
	CopyUsers(ctx context.Context, arg []*CopyUsersParams) (int64, error)
	// kind: write
	// shard: tenant(tenant_id)
	// store: Users
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	// kind: write
	// shard: all()
	// store: Users
	DeleteAllUsers(ctx context.Context) error
	// kind: write
	// shard: all()
	// store: Users
	DeleteAllUsersByName(ctx context.Context, name string) (int64, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Analyses
	GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Analyses
	GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisParams) (*GetTenantUserAnalysisRow, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Users
	GetUser(ctx context.Context, arg *GetUserParams) (*User, error)
	// kind: read
	// shard: all()
	// store: Users
	ListAllUsers(ctx context.Context) ([]*User, error)
	// kind: read
	// shard: messageKey(user_id, to_user_or_group_id, in_group)
	// store: QueryMessage
	ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatParams) ([]interface{}, error)
	// kind: read
	// shard: messageKey(user_id, to_user_or_group_id, in_group)
	// store: QueryMessage
	ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatParams) ([]*Message, error)
	// kind: read
	// shard: tenant(tenant_id)
	// store: Users
	ListUsersByIDs(ctx context.Context, ids []int64) ([]*User, error)
	// kind: write
	// shard: tenant(tenant_id)
	// store: Users
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
