// Code generated by pgmesh. DO NOT EDIT.

package samepackage

import (
	"context"
	"github.com/jackc/pgx/v5"
)

// readQueries exposes read-only generated queries.
type readQueries struct {
	main *Queries
}

func newReadQueries(q *Queries) *readQueries {
	return &readQueries{main: q}
}

// WithTx returns a read wrapper that executes queries through tx.
func (q *readQueries) WithTx(tx pgx.Tx) *readQueries {
	return newReadQueries(q.main.WithTx(tx))
}

// GetAnalysis executes the generated GetAnalysis query.
func (q *readQueries) GetAnalysis(ctx context.Context, arg *GetAnalysisParams) (*Analysis, error) {
	rv0, err := q.main.GetAnalysis(ctx, arg)
	if err != nil {
		var zero0 *Analysis
		return zero0, err
	}
	return rv0, nil
}

// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
func (q *readQueries) GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisParams) (*GetTenantUserAnalysisRow, error) {
	rv0, err := q.main.GetTenantUserAnalysis(ctx, arg)
	if err != nil {
		var zero0 *GetTenantUserAnalysisRow
		return zero0, err
	}
	return rv0, nil
}

// GetUser executes the generated GetUser query.
func (q *readQueries) GetUser(ctx context.Context, arg *GetUserParams) (*User, error) {
	rv0, err := q.main.GetUser(ctx, arg)
	if err != nil {
		var zero0 *User
		return zero0, err
	}
	return rv0, nil
}

// ListAllUsers executes the generated ListAllUsers query.
func (q *readQueries) ListAllUsers(ctx context.Context) ([]*User, error) {
	rv0, err := q.main.ListAllUsers(ctx)
	if err != nil {
		var zero0 []*User
		return zero0, err
	}
	return rv0, nil
}

// ListP2PMessageIDsByChat executes the generated ListP2PMessageIDsByChat query.
func (q *readQueries) ListP2PMessageIDsByChat(ctx context.Context, arg *ListP2PMessageIDsByChatParams) ([]interface{}, error) {
	rv0, err := q.main.ListP2PMessageIDsByChat(ctx, arg)
	if err != nil {
		var zero0 []interface{}
		return zero0, err
	}
	return rv0, nil
}

// ListP2PMessagesByChat executes the generated ListP2PMessagesByChat query.
func (q *readQueries) ListP2PMessagesByChat(ctx context.Context, arg *ListP2PMessagesByChatParams) ([]*Message, error) {
	rv0, err := q.main.ListP2PMessagesByChat(ctx, arg)
	if err != nil {
		var zero0 []*Message
		return zero0, err
	}
	return rv0, nil
}

// ListUsersByID executes the generated ListUsersByID query.
func (q *readQueries) ListUsersByID(ctx context.Context, id []int64) ([]*User, error) {
	rv0, err := q.main.ListUsersByID(ctx, id)
	if err != nil {
		var zero0 []*User
		return zero0, err
	}
	return rv0, nil
}
