// Code generated by pgmesh. DO NOT EDIT.

package samepackage

import (
	"context"
	pgmesh "github.com/sundayfun/pgmesh"
)

// GetAnalysisT is the store parameter type for GetAnalysis.
type GetAnalysisT = GetAnalysisParams

// GetTenantUserAnalysisT combines SQL and routing parameters for GetTenantUserAnalysis.
type GetTenantUserAnalysisT struct {
	UserID     int64
	AnalysisID int64
	TenantID   int64
}

func (arg *GetTenantUserAnalysisT) sqlcParams() *GetTenantUserAnalysisParams {
	return &GetTenantUserAnalysisParams{
		UserID:     arg.UserID,
		AnalysisID: arg.AnalysisID,
	}
}

// AnalysesReader exposes read queries in the Analyses store group.
type AnalysesReader interface {
	// GetAnalysis executes the generated GetAnalysis query.
	GetAnalysis(ctx context.Context, arg *GetAnalysisT, storeOptions ...QueryOption) (*Analysis, error)
	// GetTenantUserAnalysis executes the generated GetTenantUserAnalysis query.
	GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisT, storeOptions ...QueryOption) (*GetTenantUserAnalysisRow, error)
}

// AnalysesWriter exposes write queries in the Analyses store group.
type AnalysesWriter interface {
}

// Analyses exposes all queries in its generated store group.
type Analyses interface {
	AnalysesReader
	AnalysesWriter
}

type telemetryAnalysesStore[SK any] struct {
	store  *meshStore[SK]
	target Analyses
}

func (q *telemetryAnalysesStore[SK]) GetAnalysis(ctx context.Context, arg *GetAnalysisT, storeOptions ...QueryOption) (result *Analysis, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Analyses", "GetAnalysis", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetAnalysis(ctx, arg, storeOptions...)
}

func (q *telemetryAnalysesStore[SK]) GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisT, storeOptions ...QueryOption) (result *GetTenantUserAnalysisRow, err error) {
	ctx, storeSpan := q.store.mesh.StartStoreSpan(ctx, "Analyses", "GetTenantUserAnalysis", pgmesh.QueryKindRead)
	defer func() { storeSpan.End(err) }()
	return q.target.GetTenantUserAnalysis(ctx, arg, storeOptions...)
}

// WithAnalysesFactory configures an optional wrapper for the Analyses query group.
// A nil factory leaves the generated query group unwrapped.
func WithAnalysesFactory(createAnalyses func(Analyses) Analyses) StoreOption {
	return func(options *storeOptions) { options.factories.Analyses = createAnalyses }
}

var _ Analyses = (*groupedMeshStore[uint8])(nil)
var _ Analyses = (*telemetryAnalysesStore[uint8])(nil)

// Analyses returns the Analyses query group.
func (q *meshStore[SK]) Analyses() Analyses {
	return q.groups.Analyses
}

// GetAnalysis executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetAnalysis(ctx context.Context, arg *GetAnalysisT, storeOptions ...QueryOption) (result *Analysis, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Analyses", "GetAnalysis", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetAnalysis(ctx, arg)

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetAnalysis(ctx, arg)

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetAnalysis(ctx, arg)
	}
}

// GetTenantUserAnalysis executes the generated query on its target shard.
func (q *groupedMeshStore[SK]) GetTenantUserAnalysis(ctx context.Context, arg *GetTenantUserAnalysisT, storeOptions ...QueryOption) (result *GetTenantUserAnalysisRow, err error) {
	// Trace the query and record its returned error.
	ctx, querySpan := q.store.mesh.StartSpan(ctx, "Analyses", "GetTenantUserAnalysis", pgmesh.QueryKindRead)
	defer func() { querySpan.End(err) }()

	// Resolve the shard key for this topology.
	var shardKey SK
	if q.store.resolver != nil {
		shardKey = q.store.resolver.Tenant(arg.TenantID)
	}
	shard, err := q.store.mesh.Shard(shardKey)
	if err != nil {
		return result, err
	}

	// Apply options that can override the default route.
	options := applyQueryOptions(storeOptions...)

	switch {
	// Transactional reads must use their transaction.
	case options.tx != nil:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeTransaction)
		return shard.Write().WithTx(options.tx).GetTenantUserAnalysis(ctx, arg.sqlcParams())

	// Explicit primary reads bypass replicas.
	case options.primary:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModePrimary)
		return shard.Write().GetTenantUserAnalysis(ctx, arg.sqlcParams())

	// Ordinary reads use the shard's replica route.
	default:
		querySpan.SetRoute(shard.VShardIndex(), shard.Name(), pgmesh.RouteModeRead)
		return shard.Read().GetTenantUserAnalysis(ctx, arg.sqlcParams())
	}
}
